const COPY = {
  en: {
    finalReport: 'Final report',
    version: 'Version',
    stale: 'Voting reopened after this report was published. The findings below reflect the earlier finalised snapshot.',
    openingTitle: 'What the room found',
    intro: ({ voterCount, statementCount, responseCount }) =>
      `${voterCount} people voted across ${statementCount} statements, contributing ${responseCount} responses. This report follows the strongest shared signals first, then shows where the conversation remains open.`,
    limitedDataTitle: 'Limited data — treat these insights as early signals',
    limitedDataNotice: ({ voterCount, statementCount }) =>
      `${voterCount} people voted on ${statementCount} statements. The report still shows patterns in their recorded responses, but there is not enough evidence for reliable or generalisable conclusions.`,
    voters: 'people voted',
    statements: 'statements',
    responses: 'responses',
    takeawaysKicker: 'The story in brief',
    takeawaysTitle: 'Three findings to carry forward',
    takeawaysLead: 'These are the strongest shared signals and the most important evidence caveat.',
    support: 'support',
    stronglyAgree: 'strongly agree',
    agree: 'agree',
    neutral: 'neutral',
    oppose: 'disagree',
    disagree: 'disagree',
    stronglyDisagree: 'strongly disagree',
    coverage: 'coverage',
    fewerResponses: ' · fewer responses',
    evidenceLabel: 'Voting evidence',
    moreEvidence: (count) => `${count} more supporting statement${count === 1 ? '' : 's'}`,
    commonKicker: 'Common ground',
    commonTitle: 'Common ground is about how policy should work',
    commonLead: 'These key response patterns combine shared signals, different policy approaches, and an important caveat.',
    neutralKicker: 'Worth a closer look',
    neutralTitle: 'Where people paused before taking a side',
    neutralLead: 'These statements received the highest share of observed neutral responses. Neutral is not the same as missing, and the vote alone cannot tell us why somebody chose it.',
    principlesKicker: 'Principles beneath the votes',
    principlesTitle: 'The values connecting these results',
    principlesLead: 'These principles summarise recurring ideas across several pieces of voting evidence.',
    actionKicker: 'From evidence to action',
    actionTitle: 'Areas to carry into implementation',
    actionLead: 'These are evidence-linked directions for testing and discussion. They are an editorial synthesis, not a package endorsed by participants.',
    overlapKicker: 'Held together',
    overlapTitle: 'People supported more than one priority at once',
    overlapLead: 'The voting did not always force an either-or choice. These overlaps show priorities that many participants held together.',
    both: 'supported both',
    supportedBoth: 'supported both',
    leftOnly: 'only the first',
    rightOnly: 'only the second',
    neither: 'neither',
    jointResponses: 'people responded to both',
    coverageKicker: 'Strength of evidence',
    coverageTitle: 'How fully the room responded',
    coverageLead: 'Response coverage varies by statement. Lower reach means weaker evidence; it does not mean disagreement.',
    overallResponsePattern: 'Pattern across all recorded responses',
    averageCoverage: 'average coverage',
    lowestCoverage: 'lowest coverage',
    lowerReachStatements: 'statements below 50%',
    lowerReach: 'lower reach',
    coverageSegmentLabels: ['First third', 'Middle third', 'Final third'],
    coverageTrendAria: 'Response coverage and answer distribution from the first to the final statement',
    coverageChartHint: 'Bar height shows response coverage; colours show the answer mix.',
    opinionKicker: 'Different emphases',
    opinionTitle: 'People combined these priorities in different ways',
    opinionLead: 'The map shows recurring patterns among people with enough responses for comparison. The tendencies can overlap and should not be read as fixed camps.',
    opinionReadingKicker: 'How to read the map',
    opinionReadingTitle: 'Two overlapping patterns—not fixed camps',
    opinionReadingIntro: 'Position shows relative emphasis, while the shaded regions show aggregate spread. The interpretation below explains what each area tends to prioritise.',
    opinionDimensionsLabel: 'Two main contrasts',
    opinionTendenciesLabel: 'Two recurring tendencies',
    opinionTendencyFallback: 'A recurring combination of voting priorities.',
    opinionReadingCaveat: 'Counts are rounded tendency weights. Because patterns overlap, they are not exclusive group assignments.',
    opinionUnavailableLead: 'This analysis looks for recurring combinations of priorities across participants’ responses.',
    opinionNeedsRegeneration: 'This report was generated before its opinion map was available. Regenerate the report to include it.',
    tendency: 'Tendency',
    opinionMapPeople: ({ count, total }) => `(${count}/${total})`,
    approximateShare: (value) => `${value} relative weight`,
    tendencyPriorities: 'Often emphasises',
    densityShown: 'people shown in privacy-safe density cells',
    densitySuppressed: 'people omitted because their cell was too small',
    dimension: 'Main dimension',
    opinionUnavailable: 'There were not enough distinct response patterns to describe opinion tendencies.',
    reliabilityKicker: 'Reliability check',
    reliabilityTitle: 'How stable is the opinion landscape?',
    hardGroupsPublishable: 'hard groups passed',
    hardGroupsWithheld: 'hard groups withheld',
    varianceExplained: 'variation shown on the map',
    eligibleParticipants: 'people included',
    excludedParticipants: 'people excluded',
    minimumVotesForMap: 'minimum votes per person',
    bootstrapAria: (completed) => `${completed} statement-bootstrap reliability runs`,
    bootstrapFrequency: (selectedK, count) => `K=${selectedK}: ${count} runs`,
    reliabilitySummary: ({ completed, median, threshold, passCount }) =>
      `${completed} resampled analyses were completed. The median adjusted Rand score was ${median == null ? 'not available' : Math.round(median * 100) + '%'} against a ${threshold == null ? '70%' : Math.round(threshold * 100) + '%'} stability threshold; ${passCount} runs met it.`,
    reliabilityCaveat: 'The map is exploratory. Overlapping tendencies describe recurring response patterns; they are not identities, fixed camps, or a representative sample of a wider population.',
    questionsKicker: 'Still open',
    questionsTitle: 'Where another conversation is needed',
    questionsLead: 'These statements produced a more even division among people who took a position.',
    proposalVerifiedKicker: 'Participant-verified common ground',
    proposalDraftKicker: 'Common-ground draft',
    proposalSectionTitle: 'AI common ground',
    proposalAgreementMetric: 'Agreement',
    proposalParticipationMetric: 'Participation',
    proposalAgreement: ({ agree, total, rate }) => `${agree} of ${total} respondents agreed (${rate})`,
    proposalParticipation: ({ total, rosterSize }) => `${total} of ${rosterSize} participants responded`,
    proposalRecommendations: 'Directions in the package',
    proposalConditions: 'Conditions and safeguards',
    proposalUnresolved: 'Still unresolved',
    proposalTradeoffs: 'Trade-offs considered',
    proposalRemainingConcerns: 'Remaining concerns',
    proposalUnvalidated: 'This proposal has not yet received participant validation.',
    nextKicker: 'What this means',
    nextTitle: 'A practical way forward',
    nextCommon: 'Start with the areas that already combine support and reach.',
    nextOpen: 'Keep the open questions visible instead of presenting them as settled.',
    nextCoverage: 'Treat lower-response findings as signals to investigate, not conclusions.',
    implicationsKicker: 'What this means',
    implicationsTitle: 'Possible implications',
    limitationsKicker: 'Read with care',
    limitationsTitle: 'What this report cannot establish',
    limitationsLead: 'These boundaries matter when turning the findings into decisions.',
    defaultLimitations: ({ lowerReachCount, hardGroupsWithheld }) => [
      {
        title: 'This is a snapshot of participants, not a population estimate',
        explanation: 'The report describes the people who voted in this session. It should not be generalised to people who did not participate.',
      },
      {
        title: 'Neutral responses do not reveal motivation',
        explanation: 'A neutral vote may reflect uncertainty, mixed views, wording, or another reason. The data records the response but cannot infer the reason.',
      },
      {
        title: 'Incomplete response coverage weakens some findings',
        explanation: lowerReachCount > 0
          ? `${lowerReachCount} statement${lowerReachCount === 1 ? '' : 's'} reached fewer than half of voters and should be treated as follow-up signals.`
          : 'Coverage still varies across statements, so comparisons should retain their response denominators.',
      },
      {
        title: hardGroupsWithheld
          ? 'The data does not support reliable hard-group claims'
          : 'Opinion groups remain an exploratory interpretation',
        explanation: hardGroupsWithheld
          ? 'The stability guardrails did not justify publishing fixed group claims. Only overlapping tendencies are shown.'
          : 'Even when stability guardrails pass, the tendencies remain overlapping analytical patterns rather than fixed identities.',
      },
    ],
    allStatementsTitle: (count) => `All ${count} statements and response patterns`,
    allStatementsIntro: 'Percentages use the people who responded to each statement as the denominator. Coverage uses all voters as the denominator.',
    statement: 'Statement',
    methodsTitle: 'How this report was produced',
    methodsIntro: 'The report is generated from the finalised voting snapshot.',
    minimumEvidence: 'Minimum evidence threshold',
    privacy: 'Privacy',
    privacyText: 'The public report contains aggregate counts only. It does not include participant identifiers or individual ballots.',
    opinionMethod: 'The opinion landscape uses a two-dimensional, Pol.is-inspired projection and overlapping tendency analysis. Shaded regions show aggregate weighted spread, not participant locations or confidence intervals.',
    narrativeMethod: 'AI was used to draft the editorial labels and explanations from aggregate evidence. It did not receive names or individual ballots, and its claims are linked to statement IDs.',
    methodInterpretation: 'How to interpret it:',
    methodSteps: ({
      voterCount,
      statementCount,
      responseCount,
      averageCoverage,
      eligibleParticipants,
      excludedParticipants,
      minimumVotes,
      explainedVariance,
      bootstrapRuns,
      bootstrapMedian,
      bootstrapThreshold,
      hardGroupStatus,
    }) => [
      {
        title: 'Freeze and validate the aggregate snapshot',
        text: `${voterCount} voters, ${statementCount} statements, and ${responseCount} valid responses were fixed for this report.`,
        meaning: 'Later voting does not silently change a published version, and the public report does not expose participant identifiers or ballots.',
      },
      {
        title: 'Calculate every statement response pattern',
        text: `Support, neutral, disagreement, and coverage were calculated separately. Average coverage was ${averageCoverage}.`,
        meaning: 'Neutral is an observed response; missing is not neutral. Statement percentages and coverage therefore use different denominators.',
      },
      {
        title: 'Synthesize principles and action areas',
        text: 'AI drafted three cross-cutting principles and up to five action areas from aggregate evidence, with each claim linked back to statement IDs.',
        meaning: 'The synthesis organises the votes for readers. It is not itself a participant-voted or endorsed package.',
      },
      {
        title: 'Measure priorities held together',
        text: 'Pairwise overlap was calculated only among people who answered both statements. Support means agree or strongly agree.',
        meaning: 'Neutral and disagreement count as not supporting that statement in the overlap, while non-responses are excluded from the pair.',
      },
      {
        title: 'Project the opinion landscape',
        text: eligibleParticipants > 0
          ? `${eligibleParticipants} people with at least ${minimumVotes} responses were included; ${excludedParticipants} were excluded. The two displayed dimensions explain ${explainedVariance} of observed variation.`
          : 'The system checked whether enough privacy-safe voting evidence existed for a two-dimensional opinion map.',
        meaning: 'The axes describe variation in emphasis, not better and worse positions. Exclusion reflects evidence requirements, not a judgment about a participant.',
      },
      {
        title: 'Describe overlapping tendencies',
        text: 'Fuzzy tendency analysis gives each eligible response pattern partial membership in two recurring tendencies.',
        meaning: 'A person can resemble more than one tendency, so these are deliberately not presented as mutually exclusive camps.',
      },
      {
        title: 'Stress-test fixed-group claims',
        text: bootstrapRuns > 0
          ? `${bootstrapRuns} statement-bootstrap runs produced a median stability score of ${bootstrapMedian}; the threshold was ${bootstrapThreshold}. Result: ${hardGroupStatus}.`
          : `The stability and publication guardrails were checked. Result: ${hardGroupStatus}.`,
        meaning: 'Hard group claims are withheld unless the resampled analyses, group size, share, and separation guardrails all support them.',
      },
    ],
    generated: 'Generated',
    controlsTitle: 'Story report',
    controlsDesc: 'Freeze the current votes and generate a reader-facing report.',
    generate: 'Finalize and create report',
    regenerate: 'Generate a new version',
    generating: 'Preparing the report…',
    preview: 'Preview draft',
    hidePreview: 'Hide preview',
    publish: 'Publish report',
    publishAndShare: 'Publish and share with participants',
    published: 'Report published',
    participantReady: 'The final report is ready for you.',
    openReport: 'Open public report',
    failed: 'The report could not be generated. Try again.',
    draftReady: 'Draft ready for review',
    staleDraft: 'Voting changed after this version was generated.',
  },
  zh: {
    finalReport: '成果報告',
    version: '版本',
    stale: '本報告發布後，投票已重新開放。以下內容反映的是先前定稿時的資料。',
    openingTitle: '這場討論告訴我們什麼',
    intro: ({ voterCount, statementCount, responseCount }) =>
      `${voterCount} 位參與者針對 ${statementCount} 項主張投票，共留下 ${responseCount} 筆回應。這份報告先呈現最明確的共同訊號，再說明仍待討論之處。`,
    limitedDataTitle: '資料有限——請將以下洞見視為初步訊號',
    limitedDataNotice: ({ voterCount, statementCount }) =>
      `${voterCount} 位參與者針對 ${statementCount} 項主張投票。本報告仍呈現已記錄回應中的模式，但目前證據不足以支持可靠或可推廣的一般性結論。`,
    voters: '位參與者投票',
    statements: '項主張',
    responses: '筆回應',
    takeawaysKicker: '先看重點',
    takeawaysTitle: '值得帶走的三項發現',
    takeawaysLead: '這些是最強的共同訊號，以及最重要的證據限制。',
    support: '支持',
    stronglyAgree: '非常同意',
    agree: '同意',
    neutral: '中立',
    oppose: '不同意',
    disagree: '不同意',
    stronglyDisagree: '非常不同意',
    coverage: '回應涵蓋率',
    fewerResponses: ' · 回應較少',
    evidenceLabel: '投票證據',
    moreEvidence: (count) => `另有 ${count} 項相關主張`,
    commonKicker: '共同基礎',
    commonTitle: '共同基礎在於政策應如何運作',
    commonLead: '這些關鍵回應模式涵蓋共同訊號、不同政策方向與一項重要限制。',
    neutralKicker: '值得進一步追問',
    neutralTitle: '哪些主張讓參與者暫不選邊',
    neutralLead: '以下主張的中立回應比例最高。中立不等於未回應，而投票資料本身也無法說明參與者選擇中立的原因。',
    principlesKicker: '投票背後的原則',
    principlesTitle: '串連這些結果的共同價值',
    principlesLead: '這些原則整理了多項投票證據中反覆出現的想法。',
    actionKicker: '從證據走向行動',
    actionTitle: '可帶入實作的行動面向',
    actionLead: '這些是與證據連結的測試與討論方向，屬於編輯性綜整，並非參與者共同表決通過的整套方案。',
    overlapKicker: '同時存在的期待',
    overlapTitle: '許多人同時支持不只一項優先目標',
    overlapLead: '投票結果不總是非此即彼。這些重疊顯示，參與者往往會同時重視不同面向。',
    both: '兩者都支持',
    supportedBoth: '同時支持兩者',
    leftOnly: '只支持第一項',
    rightOnly: '只支持第二項',
    neither: '兩者皆未支持',
    jointResponses: '位參與者皆有回應',
    coverageKicker: '證據強度',
    coverageTitle: '這場討論的回應有多完整',
    coverageLead: '各項主張的回應涵蓋率並不相同。涵蓋率較低代表證據較弱，不代表不同意。',
    overallResponsePattern: '所有有效回應的整體分布',
    averageCoverage: '平均涵蓋率',
    lowestCoverage: '最低涵蓋率',
    lowerReachStatements: '低於 50% 的主張',
    lowerReach: '涵蓋較低',
    coverageSegmentLabels: ['前段三分之一', '中段三分之一', '後段三分之一'],
    coverageTrendAria: '從第一項到最後一項主張的回應涵蓋率與答案分布',
    coverageChartHint: '長條高度顯示回應涵蓋率；顏色顯示答案分布。',
    opinionKicker: '不同的重視方式',
    opinionTitle: '參與者以不同方式組合這些優先目標',
    opinionLead: '這張圖呈現回應資料足以比較的參與者中，反覆出現的意見模式。各種傾向可能重疊，不代表固定陣營。',
    opinionReadingKicker: '如何閱讀這張圖',
    opinionReadingTitle: '兩種重疊的模式，而非固定陣營',
    opinionReadingIntro: '位置呈現相對重視方向，半透明區域呈現彙整後的分布。以下解讀說明各區域通常重視哪些面向。',
    opinionDimensionsLabel: '兩個主要差異面向',
    opinionTendenciesLabel: '兩種反覆出現的傾向',
    opinionTendencyFallback: '一種反覆出現的投票優先組合。',
    opinionReadingCaveat: '數字是四捨五入後的傾向權重。由於模式彼此重疊，它們並不是互斥的群組分配。',
    opinionUnavailableLead: '這項分析會從參與者的回答中尋找反覆出現的優先順序組合。',
    opinionNeedsRegeneration: '這份報告生成時尚未提供意見圖。請重新生成報告以加入此圖。',
    tendency: '意見傾向',
    opinionMapPeople: ({ count, total }) => `(${count}/${total})`,
    approximateShare: (value) => `相對比重 ${value}`,
    tendencyPriorities: '較常重視',
    densityShown: '位參與者呈現在符合隱私門檻的區塊中',
    densitySuppressed: '位參與者因所在區塊人數過少而未顯示',
    dimension: '主要差異面向',
    opinionUnavailable: '目前沒有足夠明確的回答模式可用來呈現意見傾向。',
    reliabilityKicker: '可靠度檢查',
    reliabilityTitle: '意見分布是否穩定？',
    hardGroupsPublishable: '固定分組通過門檻',
    hardGroupsWithheld: '不發布固定分組',
    varianceExplained: '圖中呈現的差異',
    eligibleParticipants: '納入分析人數',
    excludedParticipants: '未納入人數',
    minimumVotesForMap: '每人最低回應數',
    bootstrapAria: (completed) => `${completed} 次主張自助抽樣可靠度測試`,
    bootstrapFrequency: (selectedK, count) => `K=${selectedK}：${count} 次`,
    reliabilitySummary: ({ completed, median, threshold, passCount }) =>
      `完成 ${completed} 次重抽樣分析；調整後 Rand 指數中位數為 ${median == null ? '無資料' : Math.round(median * 100) + '%'}，穩定門檻為 ${threshold == null ? '70%' : Math.round(threshold * 100) + '%'}，其中 ${passCount} 次達標。`,
    reliabilityCaveat: '這張圖屬於探索性分析。重疊傾向描述反覆出現的回應模式，不代表個人身分、固定陣營，也不能視為更廣泛人口的代表性樣本。',
    questionsKicker: '仍待釐清',
    questionsTitle: '下一輪討論可以從這裡開始',
    questionsLead: '在有明確立場的參與者之間，以下主張呈現較平均的分歧。',
    proposalVerifiedKicker: '參與者確認的共同基礎',
    proposalDraftKicker: '共同基礎草案',
    proposalSectionTitle: 'AI 共同基礎',
    proposalAgreementMetric: '同意度',
    proposalParticipationMetric: '參與率',
    proposalAgreement: ({ agree, total, rate }) => `${total} 位回應者中，${agree} 位同意（${rate}）`,
    proposalParticipation: ({ total, rosterSize }) => `${rosterSize} 位參與者中有 ${total} 位回應`,
    proposalRecommendations: '方案中的方向',
    proposalConditions: '條件與保障措施',
    proposalUnresolved: '仍待解決',
    proposalTradeoffs: '納入考量的權衡',
    proposalRemainingConcerns: '仍存的疑慮',
    proposalUnvalidated: '這項提案尚未經參與者驗證。',
    nextKicker: '這代表什麼',
    nextTitle: '接下來可以怎麼做',
    nextCommon: '先從兼具支持度與參與廣度的主張開始行動。',
    nextOpen: '保留尚未解決的問題，不把分歧包裝成共識。',
    nextCoverage: '回應較少的結果適合作為後續探索線索，不宜直接視為結論。',
    implicationsKicker: '這代表什麼',
    implicationsTitle: '可能的啟示',
    limitationsKicker: '閱讀時請留意',
    limitationsTitle: '這份報告無法證明什麼',
    limitationsLead: '把結果轉化為決策時，需要保留以下界線。',
    defaultLimitations: ({ lowerReachCount, hardGroupsWithheld }) => [
      {
        title: '這是參與者的快照，不是母體推估',
        explanation: '本報告只描述本次參與投票的人，不能直接推論到未參與者或更廣泛的人群。',
      },
      {
        title: '中立回應不會揭示背後原因',
        explanation: '中立可能代表不確定、同時有多種看法、對文字有疑慮，或其他原因；資料只記錄選項，不能推測動機。',
      },
      {
        title: '回應不完整會削弱部分發現',
        explanation: lowerReachCount > 0
          ? `有 ${lowerReachCount} 項主張的涵蓋率低於半數，應視為後續追問的訊號。`
          : '各項主張的涵蓋率仍有差異，比較時必須保留各自的回應分母。',
      },
      {
        title: hardGroupsWithheld
          ? '資料不足以支持可靠的固定分組'
          : '意見分組仍是探索性解讀',
        explanation: hardGroupsWithheld
          ? '穩定度門檻不足以支持發布固定陣營，因此報告只呈現可重疊的傾向。'
          : '即使通過穩定門檻，這些傾向仍是可重疊的分析模式，而非固定身分。',
      },
    ],
    allStatementsTitle: (count) => `全部 ${count} 項主張與回應分布`,
    allStatementsIntro: '各選項百分比以該主張的實際回應者為分母；涵蓋率則以全部投票者為分母。',
    statement: '主張',
    methodsTitle: '這份報告如何產生',
    methodsIntro: '本報告依據定稿當下的投票資料自動產生。',
    minimumEvidence: '最低證據門檻',
    privacy: '隱私處理',
    privacyText: '公開報告只呈現彙整後的數據，不包含參與者識別資訊或個別投票紀錄。',
    opinionMethod: '意見分布採用受 Pol.is 啟發的二維投影與重疊傾向分析；半透明區域呈現彙整後的加權分布，不是個人位置或信賴區間。',
    narrativeMethod: 'AI 依據彙整後的證據草擬標題與說明，不會取得姓名或個別投票紀錄；敘事中的結論均連結至對應的主張編號。',
    methodInterpretation: '解讀方式：',
    methodSteps: ({
      voterCount,
      statementCount,
      responseCount,
      averageCoverage,
      eligibleParticipants,
      excludedParticipants,
      minimumVotes,
      explainedVariance,
      bootstrapRuns,
      bootstrapMedian,
      bootstrapThreshold,
      hardGroupStatus,
    }) => [
      {
        title: '固定並驗證彙整資料快照',
        text: `本報告固定了 ${voterCount} 位投票者、${statementCount} 項主張與 ${responseCount} 筆有效回應。`,
        meaning: '後續投票不會在未告知的情況下改變已發布版本；公開報告也不包含參與者識別資訊或個別選票。',
      },
      {
        title: '計算每項主張的回應分布',
        text: `系統分別計算支持、中立、不同意與涵蓋率；平均涵蓋率為 ${averageCoverage}。`,
        meaning: '中立是實際觀察到的回應，未回應不是中立；因此選項比例與涵蓋率使用不同分母。',
      },
      {
        title: '綜整共同原則與行動面向',
        text: 'AI 依據彙整證據草擬三項跨主張原則與最多五項行動面向，每項結論都連回主張編號。',
        meaning: '這項綜整協助讀者理解投票結果，但本身不是經參與者投票通過或背書的方案。',
      },
      {
        title: '計算同時被支持的優先目標',
        text: '成對重疊只使用同時回應兩項主張的人；支持包含同意與強烈同意。',
        meaning: '中立與不同意會計為未支持該主張；未回應者則不進入該組比較。',
      },
      {
        title: '投影意見分布',
        text: eligibleParticipants > 0
          ? `納入至少回應 ${minimumVotes} 項主張的 ${eligibleParticipants} 人，另有 ${excludedParticipants} 人未納入；兩個顯示面向共解釋 ${explainedVariance} 的觀察差異。`
          : '系統檢查是否有足夠、且符合隱私門檻的投票證據，可用於二維意見分布圖。',
        meaning: '座標軸描述重視方式的差異，不代表立場優劣；未納入只反映證據門檻，不是對參與者的評價。',
      },
      {
        title: '描述可重疊的意見傾向',
        text: '模糊傾向分析讓每一種符合資格的回應模式，可部分屬於兩種反覆出現的傾向。',
        meaning: '同一人可以接近多種傾向，因此這些傾向不會被呈現為互斥陣營。',
      },
      {
        title: '對固定分組進行壓力測試',
        text: bootstrapRuns > 0
          ? `${bootstrapRuns} 次主張自助抽樣的穩定度中位數為 ${bootstrapMedian}，門檻為 ${bootstrapThreshold}；結果：${hardGroupStatus}。`
          : `系統已檢查穩定度與發布門檻；結果：${hardGroupStatus}。`,
        meaning: '只有重抽樣結果、群組人數、比例與分離程度都通過門檻時，才允許發布固定分組結論。',
      },
    ],
    generated: '產生時間',
    controlsTitle: '成果故事報告',
    controlsDesc: '固定目前的投票資料，產生一份方便參與者閱讀的成果報告。',
    generate: '定稿並產生報告',
    regenerate: '產生新版本',
    generating: '正在整理報告⋯',
    preview: '預覽草稿',
    hidePreview: '收起預覽',
    publish: '發布報告',
    publishAndShare: '發布並分享給參與者',
    published: '報告已發布',
    participantReady: '最終報告已可查看。',
    openReport: '開啟公開報告',
    failed: '報告產生失敗，請再試一次。',
    draftReady: '草稿已完成，等待確認',
    staleDraft: '這個版本產生後，投票內容已有變動。',
  },
}

COPY.de = {
  ...COPY.en,
  finalReport: 'Abschlussbericht',
  version: 'Version',
  stale: 'Die Abstimmung wurde nach Veröffentlichung dieses Berichts wieder geöffnet. Die Ergebnisse beziehen sich auf den früheren Datenstand.',
  openingTitle: 'Was die Gruppe herausgefunden hat',
  intro: ({ voterCount, statementCount, responseCount }) =>
    `${voterCount} Personen stimmten über ${statementCount} Aussagen ab und gaben ${responseCount} Antworten. Der Bericht beginnt mit den stärksten gemeinsamen Signalen und zeigt danach die offenen Fragen.`,
  limitedDataTitle: 'Begrenzte Daten — diese Erkenntnisse sind erste Hinweise',
  limitedDataNotice: ({ voterCount, statementCount }) =>
    `${voterCount} Personen stimmten über ${statementCount} Aussagen ab. Der Bericht zeigt weiterhin Muster in den erfassten Antworten, doch die Evidenz reicht nicht für belastbare oder verallgemeinerbare Schlussfolgerungen.`,
  voters: 'Abstimmende',
  statements: 'Aussagen',
  responses: 'Antworten',
  takeawaysKicker: 'Kurz gesagt',
  takeawaysTitle: 'Drei Erkenntnisse für den weiteren Weg',
  takeawaysLead: 'Dies sind die stärksten gemeinsamen Signale und die wichtigste Grenze der Evidenz.',
  support: 'Zustimmung',
  stronglyAgree: 'stimme voll zu',
  agree: 'stimme zu',
  neutral: 'neutral',
  oppose: 'Ablehnung',
  disagree: 'stimme nicht zu',
  stronglyDisagree: 'stimme überhaupt nicht zu',
  coverage: 'Beteiligung',
  fewerResponses: ' · weniger Antworten',
  evidenceLabel: 'Abstimmungsergebnis',
  moreEvidence: (count) => `${count} weitere unterstützende Aussage${count === 1 ? '' : 'n'}`,
  commonKicker: 'Gemeinsame Grundlage',
  commonTitle: 'Gemeinsamer Boden zeigt sich darin, wie Politik funktionieren soll',
  commonLead: 'Diese zentralen Antwortmuster verbinden gemeinsame Signale, unterschiedliche politische Ansätze und einen wichtigen Vorbehalt.',
  neutralKicker: 'Genauer hinsehen',
  neutralTitle: 'Wo Menschen unentschieden blieben',
  neutralLead: 'Diese Aussagen erhielten den höchsten Anteil beobachteter neutraler Antworten. Neutral ist nicht dasselbe wie eine fehlende Antwort; aus der Abstimmung allein lässt sich der Grund nicht ableiten.',
  principlesKicker: 'Prinzipien hinter den Stimmen',
  principlesTitle: 'Welche Werte die Ergebnisse verbinden',
  principlesLead: 'Diese Prinzipien fassen wiederkehrende Gedanken aus mehreren Abstimmungsergebnissen zusammen.',
  actionKicker: 'Von der Evidenz zum Handeln',
  actionTitle: 'Handlungsfelder für die Umsetzung',
  actionLead: 'Diese evidenzbasierten Richtungen dienen dem Testen und der weiteren Diskussion. Sie sind eine redaktionelle Synthese, kein von den Teilnehmenden bestätigtes Gesamtpaket.',
  overlapKicker: 'Zusammen gedacht',
  overlapTitle: 'Mehrere Prioritäten wurden gleichzeitig unterstützt',
  overlapLead: 'Die Abstimmung verlangte nicht immer eine Entweder-oder-Entscheidung. Diese Überschneidungen zeigen Prioritäten, die viele gemeinsam vertraten.',
  both: 'beides unterstützt',
  supportedBoth: 'beides unterstützt',
  leftOnly: 'nur die erste',
  rightOnly: 'nur die zweite',
  neither: 'keine von beiden',
  jointResponses: 'Personen beantworteten beide',
  coverageKicker: 'Stärke der Evidenz',
  coverageTitle: 'Wie vollständig die Gruppe geantwortet hat',
  coverageLead: 'Die Beteiligung unterscheidet sich je Aussage. Eine geringere Reichweite bedeutet schwächere Evidenz, nicht Ablehnung.',
  overallResponsePattern: 'Muster über alle erfassten Antworten',
  averageCoverage: 'durchschnittliche Beteiligung',
  lowestCoverage: 'niedrigste Beteiligung',
  lowerReachStatements: 'Aussagen unter 50 %',
  lowerReach: 'geringere Reichweite',
  coverageSegmentLabels: ['Erstes Drittel', 'Mittleres Drittel', 'Letztes Drittel'],
  coverageTrendAria: 'Antwortabdeckung und -verteilung von der ersten bis zur letzten Aussage',
  coverageChartHint: 'Die Balkenhöhe zeigt die Beteiligung; die Farben zeigen die Antwortverteilung.',
  opinionKicker: 'Unterschiedliche Gewichtungen',
  opinionTitle: 'Prioritäten wurden unterschiedlich miteinander verbunden',
  opinionLead: 'Die Karte zeigt wiederkehrende Muster bei Personen mit genügend Antworten für einen Vergleich. Die Tendenzen können sich überschneiden und sind keine festen Lager.',
  opinionReadingKicker: 'So ist die Karte zu lesen',
  opinionReadingTitle: 'Zwei überlappende Muster – keine festen Lager',
  opinionReadingIntro: 'Die Position zeigt relative Gewichtungen, die schattierten Bereiche die aggregierte Streuung. Die Einordnung erklärt, welche Prioritäten in jedem Bereich häufiger zusammenkommen.',
  opinionDimensionsLabel: 'Zwei zentrale Kontraste',
  opinionTendenciesLabel: 'Zwei wiederkehrende Tendenzen',
  opinionTendencyFallback: 'Eine wiederkehrende Kombination von Abstimmungsprioritäten.',
  opinionReadingCaveat: 'Die Zahlen sind gerundete Tendenzgewichte. Da sich die Muster überlappen, sind sie keine eindeutigen Gruppenzuordnungen.',
  opinionUnavailableLead: 'Diese Analyse sucht nach wiederkehrenden Kombinationen von Prioritäten in den Antworten der Teilnehmenden.',
  opinionNeedsRegeneration: 'Dieser Bericht wurde erstellt, bevor seine Meinungskarte verfügbar war. Erstelle den Bericht erneut, um sie einzubeziehen.',
  tendency: 'Tendenz',
  opinionMapPeople: ({ count, total }) => `(${count}/${total})`,
  approximateShare: (value) => `${value} relatives Gewicht`,
  tendencyPriorities: 'Häufig betont',
  densityShown: 'Personen in datenschutzkonformen Dichtefeldern',
  densitySuppressed: 'Personen wegen zu kleiner Felder nicht dargestellt',
  dimension: 'Zentrale Dimension',
  opinionUnavailable: 'Es gab nicht genügend unterschiedliche Antwortmuster, um Meinungstendenzen zu beschreiben.',
  reliabilityKicker: 'Zuverlässigkeitsprüfung',
  reliabilityTitle: 'Wie stabil ist die Meinungslandschaft?',
  hardGroupsPublishable: 'feste Gruppen bestanden',
  hardGroupsWithheld: 'feste Gruppen zurückgehalten',
  varianceExplained: 'auf der Karte gezeigte Variation',
  eligibleParticipants: 'einbezogene Personen',
  excludedParticipants: 'ausgeschlossene Personen',
  minimumVotesForMap: 'Mindestzahl Antworten pro Person',
  bootstrapAria: (completed) => `${completed} Bootstrap-Zuverlässigkeitsläufe über Aussagen`,
  bootstrapFrequency: (selectedK, count) => `K=${selectedK}: ${count} Läufe`,
  reliabilitySummary: ({ completed, median, threshold, passCount }) =>
    `${completed} neu gezogene Analysen wurden abgeschlossen. Der mediane Adjusted-Rand-Wert lag bei ${median == null ? 'nicht verfügbar' : Math.round(median * 100) + '%'} gegenüber einer Stabilitätsschwelle von ${threshold == null ? '70%' : Math.round(threshold * 100) + '%'}; ${passCount} Läufe erreichten sie.`,
  reliabilityCaveat: 'Die Karte ist explorativ. Überlappende Tendenzen beschreiben wiederkehrende Antwortmuster; sie sind keine Identitäten, festen Lager oder repräsentative Stichprobe einer grösseren Bevölkerung.',
  questionsKicker: 'Noch offen',
  questionsTitle: 'Wo ein weiteres Gespräch nötig ist',
  questionsLead: 'Bei diesen Aussagen war die Gruppe unter den Personen mit klarer Position gleichmässiger geteilt.',
  proposalVerifiedKicker: 'Von Teilnehmenden bestätigte gemeinsame Grundlage',
  proposalDraftKicker: 'Entwurf einer gemeinsamen Grundlage',
  proposalSectionTitle: 'KI-gestützte gemeinsame Grundlage',
  proposalAgreementMetric: 'Zustimmung',
  proposalParticipationMetric: 'Beteiligung',
  proposalAgreement: ({ agree, total, rate }) => `${agree} von ${total} Antwortenden stimmten zu (${rate})`,
  proposalParticipation: ({ total, rosterSize }) => `${total} von ${rosterSize} Teilnehmenden antworteten`,
  proposalRecommendations: 'Richtungen im Gesamtpaket',
  proposalConditions: 'Bedingungen und Schutzvorkehrungen',
  proposalUnresolved: 'Weiterhin offen',
  proposalTradeoffs: 'Berücksichtigte Abwägungen',
  proposalRemainingConcerns: 'Verbleibende Bedenken',
  proposalUnvalidated: 'Dieser Vorschlag wurde noch nicht von Teilnehmenden bestätigt.',
  nextKicker: 'Was das bedeutet',
  nextTitle: 'Ein praktischer Weg nach vorn',
  nextCommon: 'Mit den Bereichen beginnen, die bereits Zustimmung und Reichweite verbinden.',
  nextOpen: 'Offene Fragen sichtbar lassen, statt sie als geklärt darzustellen.',
  nextCoverage: 'Ergebnisse mit weniger Antworten als Hinweise verstehen, nicht als Schlussfolgerungen.',
  implicationsKicker: 'Was das bedeutet',
  implicationsTitle: 'Mögliche Folgerungen',
  limitationsKicker: 'Mit Bedacht lesen',
  limitationsTitle: 'Was dieser Bericht nicht belegen kann',
  limitationsLead: 'Diese Grenzen sind wichtig, wenn aus den Ergebnissen Entscheidungen werden.',
  defaultLimitations: ({ lowerReachCount, hardGroupsWithheld }) => [
    {
      title: 'Dies ist eine Momentaufnahme der Teilnehmenden, keine Bevölkerungsschätzung',
      explanation: 'Der Bericht beschreibt die Personen, die in dieser Sitzung abgestimmt haben. Er lässt sich nicht auf Personen verallgemeinern, die nicht teilgenommen haben.',
    },
    {
      title: 'Neutrale Antworten zeigen keine Motivation',
      explanation: 'Eine neutrale Antwort kann Unsicherheit, gemischte Ansichten, die Formulierung oder einen anderen Grund widerspiegeln. Die Daten erfassen die Antwort, können den Grund aber nicht ableiten.',
    },
    {
      title: 'Unvollständige Beteiligung schwächt einige Befunde',
      explanation: lowerReachCount > 0
        ? `${lowerReachCount} Aussage${lowerReachCount === 1 ? '' : 'n'} erreichte${lowerReachCount === 1 ? '' : 'n'} weniger als die Hälfte der Abstimmenden und sollte${lowerReachCount === 1 ? '' : 'n'} als Hinweis für Nachfragen gelten.`
        : 'Die Beteiligung unterscheidet sich weiterhin je Aussage; Vergleiche müssen daher die jeweiligen Antwortzahlen berücksichtigen.',
    },
    {
      title: hardGroupsWithheld
        ? 'Die Daten tragen keine zuverlässigen Aussagen über feste Gruppen'
        : 'Meinungsgruppen bleiben eine explorative Interpretation',
      explanation: hardGroupsWithheld
        ? 'Die Stabilitätskriterien rechtfertigten keine Veröffentlichung fester Gruppen. Gezeigt werden nur überlappende Tendenzen.'
        : 'Auch bei bestandenen Stabilitätskriterien bleiben die Tendenzen überlappende analytische Muster und keine festen Identitäten.',
    },
  ],
  allStatementsTitle: (count) => `Alle ${count} Aussagen und Antwortmuster`,
  allStatementsIntro: 'Die Prozentwerte verwenden die Personen, die auf die jeweilige Aussage geantwortet haben, als Nenner. Die Beteiligung verwendet alle Abstimmenden.',
  statement: 'Aussage',
  methodsTitle: 'Wie dieser Bericht erstellt wurde',
  methodsIntro: 'Der Bericht wird aus dem finalisierten Abstimmungsstand erzeugt.',
  minimumEvidence: 'Mindestschwelle für Evidenz',
  privacy: 'Datenschutz',
  privacyText: 'Der öffentliche Bericht enthält nur aggregierte Zahlen, keine Kennungen oder individuellen Stimmabgaben.',
  opinionMethod: 'Die Meinungslandschaft nutzt eine von Pol.is inspirierte zweidimensionale Projektion und eine Analyse überlappender Tendenzen. Schattierte Bereiche zeigen die aggregierte gewichtete Streuung, keine Personenpositionen oder Konfidenzintervalle.',
  narrativeMethod: 'KI formulierte redaktionelle Bezeichnungen und Erklärungen aus aggregierten Daten. Sie erhielt weder Namen noch individuelle Stimmabgaben; Aussagen sind mit den jeweiligen Aussage-IDs verknüpft.',
  methodInterpretation: 'So ist es zu lesen:',
  methodSteps: ({
    voterCount,
    statementCount,
    responseCount,
    averageCoverage,
    eligibleParticipants,
    excludedParticipants,
    minimumVotes,
    explainedVariance,
    bootstrapRuns,
    bootstrapMedian,
    bootstrapThreshold,
    hardGroupStatus,
  }) => [
    {
      title: 'Aggregierte Momentaufnahme festhalten und prüfen',
      text: `${voterCount} Abstimmende, ${statementCount} Aussagen und ${responseCount} gültige Antworten wurden für diesen Bericht fixiert.`,
      meaning: 'Spätere Abstimmungen verändern eine veröffentlichte Version nicht unbemerkt; der öffentliche Bericht enthält keine Kennungen oder individuellen Stimmabgaben.',
    },
    {
      title: 'Das Antwortmuster jeder Aussage berechnen',
      text: `Zustimmung, neutrale Antworten, Ablehnung und Beteiligung wurden getrennt berechnet. Die durchschnittliche Beteiligung lag bei ${averageCoverage}.`,
      meaning: 'Neutral ist eine beobachtete Antwort, fehlend ist nicht neutral. Aussagenprozentwerte und Beteiligung verwenden deshalb unterschiedliche Nenner.',
    },
    {
      title: 'Prinzipien und Handlungsfelder zusammenfassen',
      text: 'KI entwarf aus aggregierter Evidenz drei übergreifende Prinzipien und bis zu fünf Handlungsfelder; jede Aussage ist mit Aussage-IDs belegt.',
      meaning: 'Die Synthese ordnet die Stimmen für Lesende. Sie ist selbst kein von Teilnehmenden abgestimmtes oder bestätigtes Paket.',
    },
    {
      title: 'Gemeinsam getragene Prioritäten messen',
      text: 'Paarweise Überschneidungen wurden nur unter Personen berechnet, die beide Aussagen beantworteten. Unterstützung bedeutet Zustimmung oder starke Zustimmung.',
      meaning: 'Neutral und Ablehnung zählen in der Überschneidung als Nicht-Unterstützung dieser Aussage; fehlende Antworten sind vom Paar ausgeschlossen.',
    },
    {
      title: 'Die Meinungslandschaft projizieren',
      text: eligibleParticipants > 0
        ? `${eligibleParticipants} Personen mit mindestens ${minimumVotes} Antworten wurden einbezogen; ${excludedParticipants} wurden ausgeschlossen. Die beiden Dimensionen erklären ${explainedVariance} der beobachteten Variation.`
        : 'Das System prüfte, ob genügend datenschutzkonforme Abstimmungsdaten für eine zweidimensionale Meinungskarte vorlagen.',
      meaning: 'Die Achsen beschreiben Unterschiede in der Gewichtung, nicht bessere und schlechtere Positionen. Ein Ausschluss folgt Evidenzanforderungen und ist keine Bewertung.',
    },
    {
      title: 'Überlappende Tendenzen beschreiben',
      text: 'Eine Fuzzy-Tendenzanalyse ordnet jedem geeigneten Antwortmuster eine teilweise Zugehörigkeit zu zwei wiederkehrenden Tendenzen zu.',
      meaning: 'Eine Person kann mehreren Tendenzen ähneln; deshalb werden sie nicht als gegenseitig ausschliessende Lager dargestellt.',
    },
    {
      title: 'Aussagen über feste Gruppen einem Stresstest unterziehen',
      text: bootstrapRuns > 0
        ? `${bootstrapRuns} Aussage-Bootstrap-Läufe ergaben eine mediane Stabilität von ${bootstrapMedian}; die Schwelle lag bei ${bootstrapThreshold}. Ergebnis: ${hardGroupStatus}.`
        : `Die Stabilitäts- und Veröffentlichungskriterien wurden geprüft. Ergebnis: ${hardGroupStatus}.`,
      meaning: 'Aussagen über feste Gruppen werden zurückgehalten, sofern die neu gezogenen Analysen sowie Grössen-, Anteils- und Trennungskriterien sie nicht gemeinsam stützen.',
    },
  ],
  generated: 'Erstellt',
  controlsTitle: 'Ergebnisbericht',
  controlsDesc: 'Den aktuellen Abstimmungsstand festhalten und einen verständlichen Bericht erstellen.',
  generate: 'Finalisieren und Bericht erstellen',
  regenerate: 'Neue Version erstellen',
  generating: 'Bericht wird vorbereitet…',
  preview: 'Entwurf ansehen',
  hidePreview: 'Vorschau schließen',
  publish: 'Bericht veröffentlichen',
  publishAndShare: 'Veröffentlichen und mit Teilnehmenden teilen',
  published: 'Bericht veröffentlicht',
  participantReady: 'Der Abschlussbericht ist bereit.',
  openReport: 'Öffentlichen Bericht öffnen',
  failed: 'Der Bericht konnte nicht erstellt werden. Bitte erneut versuchen.',
  draftReady: 'Entwurf zur Prüfung bereit',
  staleDraft: 'Die Abstimmung hat sich seit der Erstellung dieser Version verändert.',
}

COPY.fr = {
  ...COPY.en,
  finalReport: 'Rapport final',
  stale: 'Le vote a été rouvert après la publication de ce rapport. Les résultats ci-dessous correspondent à la version finalisée précédente.',
  openingTitle: 'Ce que le groupe a fait ressortir',
  intro: ({ voterCount, statementCount, responseCount }) =>
    `${voterCount} personnes ont voté sur ${statementCount} propositions et fourni ${responseCount} réponses. Le rapport présente d’abord les signaux communs les plus solides, puis les questions encore ouvertes.`,
  limitedDataTitle: 'Données limitées — ces enseignements sont des signaux préliminaires',
  limitedDataNotice: ({ voterCount, statementCount }) =>
    `${voterCount} personnes ont voté sur ${statementCount} propositions. Le rapport montre néanmoins les tendances des réponses enregistrées, mais les données ne suffisent pas pour tirer des conclusions fiables ou généralisables.`,
  voters: 'personnes ont voté',
  statements: 'propositions',
  responses: 'réponses',
  takeawaysKicker: 'En bref',
  takeawaysTitle: 'Trois enseignements à retenir',
  takeawaysLead: 'Voici les signaux communs les plus forts et la principale limite des données.',
  support: 'de soutien',
  stronglyAgree: 'tout à fait d’accord',
  agree: 'd’accord',
  neutral: 'neutre',
  oppose: 'en désaccord',
  disagree: 'pas d’accord',
  stronglyDisagree: 'pas du tout d’accord',
  coverage: 'de participation',
  fewerResponses: ' · moins de réponses',
  evidenceLabel: 'Résultat du vote',
  moreEvidence: (count) => `${count} autre${count === 1 ? '' : 's'} proposition${count === 1 ? '' : 's'} à l’appui`,
  commonKicker: 'Terrain d’entente',
  commonTitle: 'Le terrain d’entente porte sur la manière de faire fonctionner la politique',
  commonLead: 'Ces principaux schémas de réponse combinent des signaux communs, différentes approches et une réserve importante.',
  neutralKicker: 'À examiner de plus près',
  neutralTitle: 'Les points sur lesquels les personnes ont suspendu leur jugement',
  neutralLead: 'Ces propositions ont reçu la plus forte part de réponses neutres observées. Une réponse neutre n’est pas une absence de réponse, et le vote seul n’en révèle pas la raison.',
  principlesKicker: 'Les principes derrière les votes',
  principlesTitle: 'Les valeurs qui relient ces résultats',
  principlesLead: 'Ces principes résument des idées récurrentes dans plusieurs résultats de vote.',
  actionKicker: 'Des données à l’action',
  actionTitle: 'Des domaines à poursuivre dans la mise en œuvre',
  actionLead: 'Ces orientations, reliées aux données, servent à tester et à poursuivre la discussion. Elles constituent une synthèse éditoriale, non un ensemble approuvé par les participantes et participants.',
  overlapKicker: 'Des priorités tenues ensemble',
  overlapTitle: 'Plusieurs priorités ont été soutenues ensemble',
  overlapLead: 'Le vote n’imposait pas toujours un choix binaire. Ces chevauchements montrent les priorités que de nombreuses personnes ont soutenues simultanément.',
  both: 'ont soutenu les deux',
  supportedBoth: 'ont soutenu les deux',
  leftOnly: 'seulement la première',
  rightOnly: 'seulement la seconde',
  neither: 'aucune des deux',
  jointResponses: 'personnes ont répondu aux deux',
  coverageKicker: 'Solidité des données',
  coverageTitle: 'Dans quelle mesure le groupe a répondu',
  coverageLead: 'La participation varie selon les propositions. Une portée plus faible indique des données moins solides, pas un désaccord.',
  overallResponsePattern: 'Répartition de l’ensemble des réponses enregistrées',
  averageCoverage: 'participation moyenne',
  lowestCoverage: 'participation la plus faible',
  lowerReachStatements: 'propositions sous 50 %',
  lowerReach: 'portée plus faible',
  coverageSegmentLabels: ['Premier tiers', 'Tiers médian', 'Dernier tiers'],
  coverageTrendAria: 'Couverture et répartition des réponses de la première à la dernière proposition',
  coverageChartHint: 'La hauteur des barres indique la couverture des réponses ; les couleurs montrent leur répartition.',
  opinionKicker: 'Des accents différents',
  opinionTitle: 'Les priorités ont été combinées de différentes manières',
  opinionLead: 'La carte montre des schémas récurrents chez les personnes ayant assez répondu pour être comparées. Les tendances peuvent se chevaucher et ne constituent pas des camps fixes.',
  opinionReadingKicker: 'Comment lire la carte',
  opinionReadingTitle: 'Deux schémas qui se chevauchent, pas des camps fixes',
  opinionReadingIntro: 'La position indique les priorités relatives et les zones ombrées leur dispersion agrégée. L’interprétation précise ce que chaque zone tend à privilégier.',
  opinionDimensionsLabel: 'Deux contrastes principaux',
  opinionTendenciesLabel: 'Deux tendances récurrentes',
  opinionTendencyFallback: 'Une combinaison récurrente de priorités de vote.',
  opinionReadingCaveat: 'Les nombres sont des poids de tendance arrondis. Comme les schémas se chevauchent, ils ne constituent pas des groupes exclusifs.',
  opinionUnavailableLead: 'Cette analyse recherche des combinaisons récurrentes de priorités dans les réponses des participants.',
  opinionNeedsRegeneration: 'Ce rapport a été généré avant que sa carte d’opinion soit disponible. Régénérez le rapport pour l’inclure.',
  tendency: 'Tendance',
  opinionMapPeople: ({ count, total }) => `(${count}/${total})`,
  approximateShare: (value) => `Poids relatif ${value}`,
  tendencyPriorities: 'Souligne souvent',
  densityShown: 'personnes dans des zones conformes au seuil de confidentialité',
  densitySuppressed: 'personnes non affichées car leur zone était trop petite',
  dimension: 'Dimension principale',
  opinionUnavailable: 'Les réponses ne présentaient pas assez de schémas distincts pour décrire des tendances d’opinion.',
  reliabilityKicker: 'Contrôle de fiabilité',
  reliabilityTitle: 'Le paysage d’opinion est-il stable ?',
  hardGroupsPublishable: 'groupes fixes validés',
  hardGroupsWithheld: 'groupes fixes non publiés',
  varianceExplained: 'variation représentée sur la carte',
  eligibleParticipants: 'personnes incluses',
  excludedParticipants: 'personnes exclues',
  minimumVotesForMap: 'réponses minimales par personne',
  bootstrapAria: (completed) => `${completed} tests de fiabilité par bootstrap des propositions`,
  bootstrapFrequency: (selectedK, count) => `K=${selectedK} : ${count} analyses`,
  reliabilitySummary: ({ completed, median, threshold, passCount }) =>
    `${completed} analyses rééchantillonnées ont été effectuées. L’indice de Rand ajusté médian était de ${median == null ? 'non disponible' : Math.round(median * 100) + ' %'}, pour un seuil de stabilité de ${threshold == null ? '70 %' : Math.round(threshold * 100) + ' %'} ; ${passCount} analyses l’ont atteint.`,
  reliabilityCaveat: 'La carte est exploratoire. Les tendances qui se chevauchent décrivent des schémas de réponse récurrents ; elles ne constituent ni des identités, ni des camps fixes, ni un échantillon représentatif d’une population plus large.',
  questionsKicker: 'Encore ouvert',
  questionsTitle: 'Les sujets qui demandent encore du dialogue',
  questionsLead: 'Ces propositions ont produit un partage plus équilibré parmi les personnes ayant pris position.',
  proposalVerifiedKicker: 'Terrain d’entente validé par les participants',
  proposalDraftKicker: 'Projet de terrain d’entente',
  proposalSectionTitle: 'Terrain d’entente proposé par l’IA',
  proposalAgreementMetric: 'Accord',
  proposalParticipationMetric: 'Participation',
  proposalAgreement: ({ agree, total, rate }) => `${agree} personnes sur ${total} ont approuvé (${rate})`,
  proposalParticipation: ({ total, rosterSize }) => `${total} personnes sur ${rosterSize} ont répondu`,
  proposalRecommendations: 'Orientations de l’ensemble',
  proposalConditions: 'Conditions et garanties',
  proposalUnresolved: 'Questions encore ouvertes',
  proposalTradeoffs: 'Arbitrages examinés',
  proposalRemainingConcerns: 'Préoccupations restantes',
  proposalUnvalidated: 'Cette proposition n’a pas encore été validée par les participantes et participants.',
  nextKicker: 'Ce que cela implique',
  nextTitle: 'Une voie concrète pour la suite',
  nextCommon: 'Commencer par les domaines qui associent déjà soutien et portée.',
  nextOpen: 'Garder les questions ouvertes visibles sans les présenter comme réglées.',
  nextCoverage: 'Considérer les résultats moins renseignés comme des pistes à explorer, non comme des conclusions.',
  implicationsKicker: 'Ce que cela implique',
  implicationsTitle: 'Implications possibles',
  limitationsKicker: 'À lire avec prudence',
  limitationsTitle: 'Ce que ce rapport ne permet pas d’établir',
  limitationsLead: 'Ces limites comptent au moment de transformer les résultats en décisions.',
  defaultLimitations: ({ lowerReachCount, hardGroupsWithheld }) => [
    {
      title: 'Il s’agit d’un instantané des participantes et participants, pas d’une estimation de la population',
      explanation: 'Le rapport décrit les personnes ayant voté dans cette session. Il ne doit pas être généralisé aux personnes qui n’y ont pas participé.',
    },
    {
      title: 'Les réponses neutres ne révèlent pas les motivations',
      explanation: 'Une réponse neutre peut refléter une incertitude, des avis partagés, la formulation ou une autre raison. Les données enregistrent la réponse sans permettre d’en déduire la cause.',
    },
    {
      title: 'Une participation incomplète affaiblit certains constats',
      explanation: lowerReachCount > 0
        ? `${lowerReachCount} proposition${lowerReachCount === 1 ? '' : 's'} a${lowerReachCount === 1 ? '' : 'ont'} atteint moins de la moitié des votantes et votants et doit${lowerReachCount === 1 ? '' : 'vent'} être considérée${lowerReachCount === 1 ? '' : 's'} comme un signal à approfondir.`
        : 'La participation varie néanmoins selon les propositions ; les comparaisons doivent donc conserver leurs dénominateurs.',
    },
    {
      title: hardGroupsWithheld
        ? 'Les données ne permettent pas d’affirmer l’existence de groupes fixes fiables'
        : 'Les groupes d’opinion restent une interprétation exploratoire',
      explanation: hardGroupsWithheld
        ? 'Les garde-fous de stabilité ne justifiaient pas la publication de groupes fixes. Seules des tendances qui se chevauchent sont présentées.'
        : 'Même lorsque les garde-fous de stabilité sont satisfaits, les tendances restent des schémas analytiques qui se chevauchent, non des identités fixes.',
    },
  ],
  allStatementsTitle: (count) => `Les ${count} propositions et leurs réponses`,
  allStatementsIntro: 'Les pourcentages utilisent comme dénominateur les personnes ayant répondu à chaque proposition. La participation utilise l’ensemble des votantes et votants.',
  statement: 'Proposition',
  methodsTitle: 'Comment ce rapport a été produit',
  methodsIntro: 'Le rapport est généré à partir de l’instantané finalisé du vote.',
  minimumEvidence: 'Seuil minimal de données',
  privacy: 'Confidentialité',
  privacyText: 'Le rapport public ne contient que des données agrégées, sans identifiant ni bulletin individuel.',
  opinionMethod: 'Le paysage d’opinion utilise une projection bidimensionnelle inspirée de Pol.is et une analyse de tendances qui se chevauchent. Les zones ombrées montrent une dispersion agrégée et pondérée, pas la position de personnes ni des intervalles de confiance.',
  narrativeMethod: 'L’IA a formulé les intitulés et explications à partir de données agrégées. Elle n’a reçu aucun nom ni vote individuel, et chaque affirmation est reliée aux identifiants des propositions.',
  methodInterpretation: 'Comment l’interpréter :',
  methodSteps: ({
    voterCount,
    statementCount,
    responseCount,
    averageCoverage,
    eligibleParticipants,
    excludedParticipants,
    minimumVotes,
    explainedVariance,
    bootstrapRuns,
    bootstrapMedian,
    bootstrapThreshold,
    hardGroupStatus,
  }) => [
    {
      title: 'Figer et valider l’instantané agrégé',
      text: `${voterCount} votantes et votants, ${statementCount} propositions et ${responseCount} réponses valides ont été figés pour ce rapport.`,
      meaning: 'Les votes ultérieurs ne modifient pas silencieusement une version publiée, et le rapport public n’expose aucun identifiant ni bulletin individuel.',
    },
    {
      title: 'Calculer la répartition des réponses à chaque proposition',
      text: `Le soutien, les réponses neutres, le désaccord et la participation ont été calculés séparément. La participation moyenne était de ${averageCoverage}.`,
      meaning: 'Une réponse neutre est observée ; une absence de réponse n’est pas neutre. Les pourcentages par proposition et la participation utilisent donc des dénominateurs différents.',
    },
    {
      title: 'Synthétiser les principes et les domaines d’action',
      text: 'L’IA a formulé trois principes transversaux et jusqu’à cinq domaines d’action à partir de données agrégées, chaque affirmation étant reliée aux identifiants des propositions.',
      meaning: 'La synthèse organise les votes pour les lectrices et lecteurs. Elle ne constitue pas un ensemble voté ou approuvé par les participantes et participants.',
    },
    {
      title: 'Mesurer les priorités soutenues ensemble',
      text: 'Le chevauchement par paires a été calculé uniquement parmi les personnes ayant répondu aux deux propositions. Le soutien signifie « d’accord » ou « tout à fait d’accord ».',
      meaning: 'Une réponse neutre ou en désaccord compte comme un non-soutien dans ce chevauchement, tandis que les absences de réponse sont exclues de la paire.',
    },
    {
      title: 'Projeter le paysage d’opinion',
      text: eligibleParticipants > 0
        ? `${eligibleParticipants} personnes ayant fourni au moins ${minimumVotes} réponses ont été incluses ; ${excludedParticipants} ont été exclues. Les deux dimensions affichées expliquent ${explainedVariance} de la variation observée.`
        : 'Le système a vérifié si les données de vote étaient suffisantes et respectaient la confidentialité pour produire une carte d’opinion bidimensionnelle.',
      meaning: 'Les axes décrivent des différences d’accent, pas de meilleures ou moins bonnes positions. L’exclusion répond à une exigence de données, pas à un jugement sur une personne.',
    },
    {
      title: 'Décrire des tendances qui se chevauchent',
      text: 'L’analyse floue attribue à chaque schéma de réponse admissible une appartenance partielle à deux tendances récurrentes.',
      meaning: 'Une personne peut ressembler à plusieurs tendances ; celles-ci ne sont donc pas présentées comme des camps mutuellement exclusifs.',
    },
    {
      title: 'Soumettre les affirmations sur des groupes fixes à un test de robustesse',
      text: bootstrapRuns > 0
        ? `${bootstrapRuns} analyses bootstrap des propositions ont produit une stabilité médiane de ${bootstrapMedian}, pour un seuil de ${bootstrapThreshold}. Résultat : ${hardGroupStatus}.`
        : `Les garde-fous de stabilité et de publication ont été vérifiés. Résultat : ${hardGroupStatus}.`,
      meaning: 'Les affirmations sur des groupes fixes ne sont pas publiées tant que les analyses rééchantillonnées et les seuils de taille, de part et de séparation ne les soutiennent pas tous.',
    },
  ],
  generated: 'Généré',
  controlsTitle: 'Rapport de résultats',
  controlsDesc: 'Figer les votes actuels et créer un rapport accessible aux participantes et participants.',
  generate: 'Finaliser et créer le rapport',
  regenerate: 'Créer une nouvelle version',
  generating: 'Préparation du rapport…',
  preview: 'Prévisualiser',
  hidePreview: 'Fermer l’aperçu',
  publish: 'Publier le rapport',
  publishAndShare: 'Publier et partager avec les participants',
  published: 'Rapport publié',
  participantReady: 'Le rapport final est prêt à être consulté.',
  openReport: 'Ouvrir le rapport public',
  failed: 'Le rapport n’a pas pu être généré. Veuillez réessayer.',
  draftReady: 'Brouillon prêt à être vérifié',
  staleDraft: 'Le vote a changé depuis la création de cette version.',
}

COPY.it = {
  ...COPY.en,
  finalReport: 'Rapporto finale',
  stale: 'La votazione è stata riaperta dopo la pubblicazione del rapporto. I risultati riflettono la precedente istantanea finalizzata.',
  openingTitle: 'Che cosa è emerso dal gruppo',
  intro: ({ voterCount, statementCount, responseCount }) =>
    `${voterCount} persone hanno votato su ${statementCount} affermazioni, fornendo ${responseCount} risposte. Il rapporto parte dai segnali condivisi più solidi e passa poi alle questioni ancora aperte.`,
  limitedDataTitle: 'Dati limitati — considera questi risultati come segnali preliminari',
  limitedDataNotice: ({ voterCount, statementCount }) =>
    `${voterCount} persone hanno votato su ${statementCount} affermazioni. Il rapporto mostra comunque gli schemi nelle risposte registrate, ma i dati non bastano per conclusioni affidabili o generalizzabili.`,
  voters: 'persone hanno votato',
  statements: 'affermazioni',
  responses: 'risposte',
  takeawaysKicker: 'In breve',
  takeawaysTitle: 'Tre risultati da portare avanti',
  takeawaysLead: 'Questi sono i segnali condivisi più forti e il limite probatorio più importante.',
  support: 'sostegno',
  stronglyAgree: 'pienamente d’accordo',
  agree: 'd’accordo',
  neutral: 'neutrale',
  oppose: 'disaccordo',
  disagree: 'in disaccordo',
  stronglyDisagree: 'fortemente in disaccordo',
  coverage: 'partecipazione',
  fewerResponses: ' · meno risposte',
  evidenceLabel: 'Risultato del voto',
  moreEvidence: (count) => `${count} altr${count === 1 ? 'a' : 'e'} affermazion${count === 1 ? 'e' : 'i'} a sostegno`,
  commonKicker: 'Terreno comune',
  commonTitle: 'Il terreno comune riguarda come dovrebbe funzionare la politica',
  commonLead: 'Questi schemi di risposta chiave combinano segnali condivisi, approcci diversi e un’importante cautela.',
  neutralKicker: 'Da osservare più da vicino',
  neutralTitle: 'Dove le persone hanno sospeso il giudizio',
  neutralLead: 'Queste affermazioni hanno ricevuto la quota più alta di risposte neutrali osservate. Neutrale non significa mancata risposta e il voto, da solo, non ne rivela il motivo.',
  principlesKicker: 'I principi dietro i voti',
  principlesTitle: 'I valori che collegano questi risultati',
  principlesLead: 'Questi principi riassumono idee ricorrenti in più risultati della votazione.',
  actionKicker: 'Dai dati all’azione',
  actionTitle: 'Ambiti da portare nell’attuazione',
  actionLead: 'Queste direzioni, collegate ai dati, servono per sperimentare e proseguire il confronto. Sono una sintesi editoriale, non un pacchetto approvato dai partecipanti.',
  overlapKicker: 'Priorità tenute insieme',
  overlapTitle: 'Più priorità sono state sostenute insieme',
  overlapLead: 'La votazione non imponeva sempre una scelta alternativa. Queste sovrapposizioni mostrano priorità sostenute contemporaneamente da molte persone.',
  both: 'hanno sostenuto entrambe',
  supportedBoth: 'hanno sostenuto entrambe',
  leftOnly: 'solo la prima',
  rightOnly: 'solo la seconda',
  neither: 'nessuna delle due',
  jointResponses: 'persone hanno risposto a entrambe',
  coverageKicker: 'Solidità dei dati',
  coverageTitle: 'Quanto è stata completa la risposta del gruppo',
  coverageLead: 'La partecipazione varia tra le affermazioni. Una portata inferiore significa dati meno solidi, non disaccordo.',
  overallResponsePattern: 'Distribuzione di tutte le risposte registrate',
  averageCoverage: 'partecipazione media',
  lowestCoverage: 'partecipazione minima',
  lowerReachStatements: 'affermazioni sotto il 50%',
  lowerReach: 'portata inferiore',
  coverageSegmentLabels: ['Primo terzo', 'Terzo centrale', 'Ultimo terzo'],
  coverageTrendAria: 'Copertura e distribuzione delle risposte dalla prima all’ultima proposta',
  coverageChartHint: 'L’altezza delle barre mostra la copertura delle risposte; i colori ne mostrano la distribuzione.',
  opinionKicker: 'Accenti diversi',
  opinionTitle: 'Le priorità sono state combinate in modi diversi',
  opinionLead: 'La mappa mostra schemi ricorrenti tra le persone con abbastanza risposte per il confronto. Le tendenze possono sovrapporsi e non sono schieramenti fissi.',
  opinionReadingKicker: 'Come leggere la mappa',
  opinionReadingTitle: 'Due schemi sovrapposti, non schieramenti fissi',
  opinionReadingIntro: 'La posizione mostra l’enfasi relativa, mentre le aree ombreggiate mostrano la dispersione aggregata. L’interpretazione spiega quali priorità caratterizzano ciascuna area.',
  opinionDimensionsLabel: 'Due contrasti principali',
  opinionTendenciesLabel: 'Due tendenze ricorrenti',
  opinionTendencyFallback: 'Una combinazione ricorrente di priorità di voto.',
  opinionReadingCaveat: 'I numeri sono pesi di tendenza arrotondati. Poiché gli schemi si sovrappongono, non rappresentano gruppi esclusivi.',
  opinionUnavailableLead: 'Questa analisi cerca combinazioni ricorrenti di priorità nelle risposte dei partecipanti.',
  opinionNeedsRegeneration: 'Questo rapporto è stato generato prima che la sua mappa delle opinioni fosse disponibile. Rigenera il rapporto per includerla.',
  tendency: 'Tendenza',
  opinionMapPeople: ({ count, total }) => `(${count}/${total})`,
  approximateShare: (value) => `Peso relativo ${value}`,
  tendencyPriorities: 'Sottolinea spesso',
  densityShown: 'persone nelle aree conformi alla soglia di riservatezza',
  densitySuppressed: 'persone non mostrate perché la loro area era troppo piccola',
  dimension: 'Dimensione principale',
  opinionUnavailable: 'Non c’erano schemi di risposta abbastanza distinti per descrivere le tendenze di opinione.',
  reliabilityKicker: 'Controllo di affidabilità',
  reliabilityTitle: 'Quanto è stabile il panorama delle opinioni?',
  hardGroupsPublishable: 'gruppi fissi validati',
  hardGroupsWithheld: 'gruppi fissi non pubblicati',
  varianceExplained: 'variazione mostrata sulla mappa',
  eligibleParticipants: 'persone incluse',
  excludedParticipants: 'persone escluse',
  minimumVotesForMap: 'risposte minime per persona',
  bootstrapAria: (completed) => `${completed} test bootstrap di affidabilità sulle affermazioni`,
  bootstrapFrequency: (selectedK, count) => `K=${selectedK}: ${count} analisi`,
  reliabilitySummary: ({ completed, median, threshold, passCount }) =>
    `Sono state completate ${completed} analisi ricampionate. L’indice di Rand corretto mediano è stato ${median == null ? 'non disponibile' : Math.round(median * 100) + '%'}, rispetto a una soglia di stabilità del ${threshold == null ? '70%' : Math.round(threshold * 100) + '%'}; ${passCount} analisi l’hanno raggiunta.`,
  reliabilityCaveat: 'La mappa è esplorativa. Le tendenze sovrapposte descrivono schemi di risposta ricorrenti; non sono identità, schieramenti fissi né un campione rappresentativo di una popolazione più ampia.',
  questionsKicker: 'Ancora aperto',
  questionsTitle: 'Dove serve un altro confronto',
  questionsLead: 'Queste affermazioni hanno diviso in modo più equilibrato le persone che hanno preso posizione.',
  proposalVerifiedKicker: 'Terreno comune verificato dai partecipanti',
  proposalDraftKicker: 'Bozza di terreno comune',
  proposalSectionTitle: 'Terreno comune proposto dall’IA',
  proposalAgreementMetric: 'Accordo',
  proposalParticipationMetric: 'Partecipazione',
  proposalAgreement: ({ agree, total, rate }) => `${agree} partecipanti su ${total} hanno approvato (${rate})`,
  proposalParticipation: ({ total, rosterSize }) => `${total} partecipanti su ${rosterSize} hanno risposto`,
  proposalRecommendations: 'Direzioni del pacchetto',
  proposalConditions: 'Condizioni e garanzie',
  proposalUnresolved: 'Questioni ancora aperte',
  proposalTradeoffs: 'Compromessi considerati',
  proposalRemainingConcerns: 'Preoccupazioni residue',
  proposalUnvalidated: 'Questa proposta non è ancora stata validata dai partecipanti.',
  nextKicker: 'Che cosa significa',
  nextTitle: 'Un percorso pratico per il futuro',
  nextCommon: 'Partire dagli ambiti che già uniscono sostegno e portata.',
  nextOpen: 'Mantenere visibili le questioni aperte senza presentarle come risolte.',
  nextCoverage: 'Trattare i risultati con meno risposte come segnali da approfondire, non come conclusioni.',
  implicationsKicker: 'Che cosa significa',
  implicationsTitle: 'Possibili implicazioni',
  limitationsKicker: 'Da leggere con cautela',
  limitationsTitle: 'Che cosa questo rapporto non può stabilire',
  limitationsLead: 'Questi limiti sono importanti quando i risultati vengono tradotti in decisioni.',
  defaultLimitations: ({ lowerReachCount, hardGroupsWithheld }) => [
    {
      title: 'È un’istantanea dei partecipanti, non una stima della popolazione',
      explanation: 'Il rapporto descrive le persone che hanno votato in questa sessione. Non va generalizzato a chi non ha partecipato.',
    },
    {
      title: 'Le risposte neutrali non rivelano le motivazioni',
      explanation: 'Una risposta neutrale può riflettere incertezza, opinioni miste, la formulazione o un altro motivo. I dati registrano la risposta ma non consentono di dedurne la causa.',
    },
    {
      title: 'Una partecipazione incompleta indebolisce alcuni risultati',
      explanation: lowerReachCount > 0
        ? `${lowerReachCount} affermazion${lowerReachCount === 1 ? 'e ha' : 'i hanno'} raggiunto meno della metà dei votanti e ${lowerReachCount === 1 ? 'va' : 'vanno'} trattat${lowerReachCount === 1 ? 'a' : 'e'} come segnal${lowerReachCount === 1 ? 'e' : 'i'} da approfondire.`
        : 'La partecipazione varia comunque tra le affermazioni, quindi i confronti devono mantenere i rispettivi denominatori.',
    },
    {
      title: hardGroupsWithheld
        ? 'I dati non sostengono affermazioni affidabili su gruppi fissi'
        : 'I gruppi di opinione restano un’interpretazione esplorativa',
      explanation: hardGroupsWithheld
        ? 'I criteri di stabilità non giustificavano la pubblicazione di gruppi fissi. Sono mostrate soltanto tendenze sovrapposte.'
        : 'Anche quando i criteri di stabilità sono soddisfatti, le tendenze restano schemi analitici sovrapposti, non identità fisse.',
    },
  ],
  allStatementsTitle: (count) => `Tutte le ${count} affermazioni e le relative risposte`,
  allStatementsIntro: 'Le percentuali usano come denominatore le persone che hanno risposto a ciascuna affermazione. La partecipazione usa tutti i votanti.',
  statement: 'Affermazione',
  methodsTitle: 'Come è stato prodotto il rapporto',
  methodsIntro: 'Il rapporto viene generato dall’istantanea finale della votazione.',
  minimumEvidence: 'Soglia minima di evidenza',
  privacy: 'Riservatezza',
  privacyText: 'Il rapporto pubblico contiene solo dati aggregati, senza identificativi o voti individuali.',
  opinionMethod: 'Il panorama delle opinioni usa una proiezione bidimensionale ispirata a Pol.is e un’analisi di tendenze sovrapposte. Le aree ombreggiate mostrano la dispersione aggregata e ponderata, non posizioni individuali o intervalli di confidenza.',
  narrativeMethod: 'L’IA ha formulato titoli e spiegazioni a partire da dati aggregati. Non ha ricevuto nomi o voti individuali e ogni affermazione è collegata agli identificativi delle proposte.',
  methodInterpretation: 'Come interpretarlo:',
  methodSteps: ({
    voterCount,
    statementCount,
    responseCount,
    averageCoverage,
    eligibleParticipants,
    excludedParticipants,
    minimumVotes,
    explainedVariance,
    bootstrapRuns,
    bootstrapMedian,
    bootstrapThreshold,
    hardGroupStatus,
  }) => [
    {
      title: 'Bloccare e validare l’istantanea aggregata',
      text: `Per questo rapporto sono stati fissati ${voterCount} votanti, ${statementCount} affermazioni e ${responseCount} risposte valide.`,
      meaning: 'I voti successivi non modificano silenziosamente una versione pubblicata e il rapporto pubblico non espone identificativi né schede individuali.',
    },
    {
      title: 'Calcolare la distribuzione delle risposte per ogni affermazione',
      text: `Sostegno, risposte neutrali, disaccordo e partecipazione sono stati calcolati separatamente. La partecipazione media è stata del ${averageCoverage}.`,
      meaning: 'Neutrale è una risposta osservata; una risposta mancante non è neutrale. Le percentuali per affermazione e la partecipazione usano quindi denominatori diversi.',
    },
    {
      title: 'Sintetizzare principi e ambiti di azione',
      text: 'L’IA ha formulato tre principi trasversali e fino a cinque ambiti di azione a partire da dati aggregati, collegando ogni affermazione agli identificativi delle proposte.',
      meaning: 'La sintesi organizza i voti per chi legge. Non è un pacchetto votato o approvato dai partecipanti.',
    },
    {
      title: 'Misurare le priorità sostenute insieme',
      text: 'La sovrapposizione a coppie è stata calcolata soltanto tra le persone che hanno risposto a entrambe le affermazioni. Sostegno significa accordo o forte accordo.',
      meaning: 'Neutrale e disaccordo contano come mancato sostegno a quella affermazione, mentre le mancate risposte sono escluse dalla coppia.',
    },
    {
      title: 'Proiettare il panorama delle opinioni',
      text: eligibleParticipants > 0
        ? `Sono state incluse ${eligibleParticipants} persone con almeno ${minimumVotes} risposte; ${excludedParticipants} sono state escluse. Le due dimensioni mostrate spiegano il ${explainedVariance} della variazione osservata.`
        : 'Il sistema ha verificato se esistessero dati di voto sufficienti e compatibili con la riservatezza per una mappa bidimensionale delle opinioni.',
      meaning: 'Gli assi descrivono differenze di enfasi, non posizioni migliori o peggiori. L’esclusione riflette requisiti di evidenza, non un giudizio sulla persona.',
    },
    {
      title: 'Descrivere tendenze sovrapposte',
      text: 'L’analisi fuzzy assegna a ogni schema di risposta idoneo un’appartenenza parziale a due tendenze ricorrenti.',
      meaning: 'Una persona può assomigliare a più di una tendenza, quindi queste non sono presentate come schieramenti mutuamente esclusivi.',
    },
    {
      title: 'Sottoporre a stress test le affermazioni sui gruppi fissi',
      text: bootstrapRuns > 0
        ? `${bootstrapRuns} analisi bootstrap sulle affermazioni hanno prodotto una stabilità mediana del ${bootstrapMedian}; la soglia era ${bootstrapThreshold}. Risultato: ${hardGroupStatus}.`
        : `Sono stati verificati i criteri di stabilità e pubblicazione. Risultato: ${hardGroupStatus}.`,
      meaning: 'Le affermazioni sui gruppi fissi non vengono pubblicate finché le analisi ricampionate e i criteri di dimensione, quota e separazione non le sostengono tutte.',
    },
  ],
  generated: 'Generato',
  controlsTitle: 'Rapporto dei risultati',
  controlsDesc: 'Fissa i voti attuali e crea un rapporto comprensibile per chi ha partecipato.',
  generate: 'Finalizza e crea il rapporto',
  regenerate: 'Crea una nuova versione',
  generating: 'Preparazione del rapporto…',
  preview: 'Anteprima',
  hidePreview: 'Chiudi anteprima',
  publish: 'Pubblica il rapporto',
  publishAndShare: 'Pubblica e condividi con i partecipanti',
  published: 'Rapporto pubblicato',
  participantReady: 'Il rapporto finale è pronto per essere consultato.',
  openReport: 'Apri il rapporto pubblico',
  failed: 'Non è stato possibile generare il rapporto. Riprova.',
  draftReady: 'Bozza pronta per la revisione',
  staleDraft: 'La votazione è cambiata da quando è stata creata questa versione.',
}

export function getReportCopy(language) {
  return COPY[language] || COPY.en
}
