const COPY = {
  en: {
    finalReport: 'Final report',
    version: 'Version',
    stale: 'Voting reopened after this report was published. The findings below reflect the earlier finalised snapshot.',
    openingTitle: 'What the room found',
    intro: ({ voterCount, statementCount, responseCount }) =>
      `${voterCount} people voted across ${statementCount} statements, contributing ${responseCount} responses. This report follows the strongest shared signals first, then shows where the conversation remains open.`,
    voters: 'people voted',
    statements: 'statements',
    responses: 'responses',
    takeawaysKicker: 'The story in brief',
    takeawaysTitle: 'Three findings to carry forward',
    takeawaysLead: 'These statements combine broad support with meaningful participation.',
    support: 'support',
    coverage: 'coverage',
    commonKicker: 'Common ground',
    commonTitle: 'Where the room can begin',
    commonLead: 'These positions received the strongest combination of support and response coverage.',
    overlapKicker: 'Held together',
    overlapTitle: 'People supported more than one priority at once',
    overlapLead: 'The voting did not always force an either-or choice. These overlaps show priorities that many participants held together.',
    both: 'supported both',
    leftOnly: 'only the first',
    rightOnly: 'only the second',
    neither: 'neither',
    jointResponses: 'people responded to both',
    questionsKicker: 'Still open',
    questionsTitle: 'Where another conversation is needed',
    questionsLead: 'These statements produced a more even division among people who took a position.',
    proposalKicker: 'A possible bridge',
    proposalTitle: 'The common-ground proposal',
    participantValidation: 'Participant validation',
    agreed: 'agreed',
    disagreed: 'disagreed',
    proposalUnvalidated: 'This proposal has not yet received participant validation.',
    nextKicker: 'What this means',
    nextTitle: 'A practical way forward',
    nextCommon: 'Start with the areas that already combine support and reach.',
    nextOpen: 'Keep the open questions visible instead of presenting them as settled.',
    nextCoverage: 'Treat lower-response findings as signals to investigate, not conclusions.',
    methodsTitle: 'How this report was produced',
    methodsIntro: 'The report is generated from the finalised voting snapshot.',
    minimumEvidence: 'Minimum evidence threshold',
    privacy: 'Privacy',
    privacyText: 'The public report contains aggregate counts only. It does not include participant identifiers or individual ballots.',
    generated: 'Generated',
    controlsTitle: 'Story report',
    controlsDesc: 'Freeze the current votes and generate a reader-facing report.',
    generate: 'Finalize and create report',
    regenerate: 'Generate a new version',
    generating: 'Preparing the report…',
    preview: 'Preview draft',
    hidePreview: 'Hide preview',
    publish: 'Publish report',
    published: 'Report published',
    openReport: 'Open public report',
    failed: 'The report could not be generated. Try again.',
    draftReady: 'Draft ready for review',
    staleDraft: 'Voting changed after this version was generated.',
  },
  zh: {
    finalReport: '成果報告',
    version: '版本',
    stale: '本報告發布後，投票已重新開放。以下內容反映的是先前定稿時的資料。',
    openingTitle: '這場討論告訴我們什麼',
    intro: ({ voterCount, statementCount, responseCount }) =>
      `${voterCount} 位參與者針對 ${statementCount} 項主張投票，共留下 ${responseCount} 筆回應。這份報告先呈現最明確的共同訊號，再說明仍待討論之處。`,
    voters: '位參與者投票',
    statements: '項主張',
    responses: '筆回應',
    takeawaysKicker: '先看重點',
    takeawaysTitle: '值得帶走的三項發現',
    takeawaysLead: '這些主張同時獲得較廣泛的支持，也有足夠的參與基礎。',
    support: '支持',
    coverage: '回應涵蓋率',
    commonKicker: '共同基礎',
    commonTitle: '可以從哪些共識開始',
    commonLead: '以下主張兼具較高支持度與回應涵蓋率，是這場討論中最穩固的共同基礎。',
    overlapKicker: '同時存在的期待',
    overlapTitle: '許多人同時支持不只一項優先目標',
    overlapLead: '投票結果不總是非此即彼。這些重疊顯示，參與者往往會同時重視不同面向。',
    both: '兩者都支持',
    leftOnly: '只支持第一項',
    rightOnly: '只支持第二項',
    neither: '兩者皆未支持',
    jointResponses: '位參與者皆有回應',
    questionsKicker: '仍待釐清',
    questionsTitle: '下一輪討論可以從這裡開始',
    questionsLead: '在有明確立場的參與者之間，以下主張呈現較平均的分歧。',
    proposalKicker: '可能的連結',
    proposalTitle: '共同基礎提案',
    participantValidation: '參與者驗證',
    agreed: '同意',
    disagreed: '不同意',
    proposalUnvalidated: '這項提案尚未經參與者驗證。',
    nextKicker: '這代表什麼',
    nextTitle: '接下來可以怎麼做',
    nextCommon: '先從兼具支持度與參與廣度的主張開始行動。',
    nextOpen: '保留尚未解決的問題，不把分歧包裝成共識。',
    nextCoverage: '回應較少的結果適合作為後續探索線索，不宜直接視為結論。',
    methodsTitle: '這份報告如何產生',
    methodsIntro: '本報告依據定稿當下的投票資料自動產生。',
    minimumEvidence: '最低證據門檻',
    privacy: '隱私處理',
    privacyText: '公開報告只呈現彙整後的數據，不包含參與者識別資訊或個別投票紀錄。',
    generated: '產生時間',
    controlsTitle: '成果故事報告',
    controlsDesc: '固定目前的投票資料，產生一份方便參與者閱讀的成果報告。',
    generate: '定稿並產生報告',
    regenerate: '產生新版本',
    generating: '正在整理報告⋯',
    preview: '預覽草稿',
    hidePreview: '收起預覽',
    publish: '發布報告',
    published: '報告已發布',
    openReport: '開啟公開報告',
    failed: '報告產生失敗，請再試一次。',
    draftReady: '草稿已完成，等待確認',
    staleDraft: '這個版本產生後，投票內容已有變動。',
  },
}

COPY.de = {
  ...COPY.en,
  finalReport: 'Abschlussbericht',
  version: 'Version',
  stale: 'Die Abstimmung wurde nach Veröffentlichung dieses Berichts wieder geöffnet. Die Ergebnisse beziehen sich auf den früheren Datenstand.',
  openingTitle: 'Was die Gruppe herausgefunden hat',
  intro: ({ voterCount, statementCount, responseCount }) =>
    `${voterCount} Personen stimmten über ${statementCount} Aussagen ab und gaben ${responseCount} Antworten. Der Bericht beginnt mit den stärksten gemeinsamen Signalen und zeigt danach die offenen Fragen.`,
  voters: 'Abstimmende',
  statements: 'Aussagen',
  responses: 'Antworten',
  takeawaysTitle: 'Drei Erkenntnisse für den weiteren Weg',
  commonTitle: 'Wo die Gruppe beginnen kann',
  overlapTitle: 'Mehrere Prioritäten wurden gleichzeitig unterstützt',
  questionsTitle: 'Wo ein weiteres Gespräch nötig ist',
  proposalTitle: 'Der Vorschlag für eine gemeinsame Grundlage',
  nextTitle: 'Ein praktischer Weg nach vorn',
  methodsTitle: 'Wie dieser Bericht erstellt wurde',
  controlsTitle: 'Ergebnisbericht',
  controlsDesc: 'Den aktuellen Abstimmungsstand festhalten und einen verständlichen Bericht erstellen.',
  generate: 'Finalisieren und Bericht erstellen',
  regenerate: 'Neue Version erstellen',
  generating: 'Bericht wird vorbereitet…',
  preview: 'Entwurf ansehen',
  hidePreview: 'Vorschau schließen',
  publish: 'Bericht veröffentlichen',
  published: 'Bericht veröffentlicht',
  openReport: 'Öffentlichen Bericht öffnen',
  draftReady: 'Entwurf zur Prüfung bereit',
}

COPY.fr = {
  ...COPY.en,
  finalReport: 'Rapport final',
  stale: 'Le vote a été rouvert après la publication de ce rapport. Les résultats ci-dessous correspondent à la version finalisée précédente.',
  openingTitle: 'Ce que le groupe a fait ressortir',
  intro: ({ voterCount, statementCount, responseCount }) =>
    `${voterCount} personnes ont voté sur ${statementCount} propositions et fourni ${responseCount} réponses. Le rapport présente d’abord les signaux communs les plus solides, puis les questions encore ouvertes.`,
  voters: 'personnes ont voté',
  statements: 'propositions',
  responses: 'réponses',
  takeawaysTitle: 'Trois enseignements à retenir',
  commonTitle: 'Les points de départ communs',
  overlapTitle: 'Plusieurs priorités ont été soutenues ensemble',
  questionsTitle: 'Les sujets qui demandent encore du dialogue',
  proposalTitle: 'La proposition de terrain d’entente',
  nextTitle: 'Une voie concrète pour la suite',
  methodsTitle: 'Comment ce rapport a été produit',
  controlsTitle: 'Rapport de résultats',
  controlsDesc: 'Figer les votes actuels et créer un rapport accessible aux participantes et participants.',
  generate: 'Finaliser et créer le rapport',
  regenerate: 'Créer une nouvelle version',
  generating: 'Préparation du rapport…',
  preview: 'Prévisualiser',
  hidePreview: 'Fermer l’aperçu',
  publish: 'Publier le rapport',
  published: 'Rapport publié',
  openReport: 'Ouvrir le rapport public',
  draftReady: 'Brouillon prêt à être vérifié',
}

COPY.it = {
  ...COPY.en,
  finalReport: 'Rapporto finale',
  stale: 'La votazione è stata riaperta dopo la pubblicazione del rapporto. I risultati riflettono la precedente istantanea finalizzata.',
  openingTitle: 'Che cosa è emerso dal gruppo',
  intro: ({ voterCount, statementCount, responseCount }) =>
    `${voterCount} persone hanno votato su ${statementCount} affermazioni, fornendo ${responseCount} risposte. Il rapporto parte dai segnali condivisi più solidi e passa poi alle questioni ancora aperte.`,
  voters: 'persone hanno votato',
  statements: 'affermazioni',
  responses: 'risposte',
  takeawaysTitle: 'Tre risultati da portare avanti',
  commonTitle: 'Da dove può partire il gruppo',
  overlapTitle: 'Più priorità sono state sostenute insieme',
  questionsTitle: 'Dove serve un altro confronto',
  proposalTitle: 'La proposta di terreno comune',
  nextTitle: 'Un percorso pratico per il futuro',
  methodsTitle: 'Come è stato prodotto il rapporto',
  controlsTitle: 'Rapporto dei risultati',
  controlsDesc: 'Fissa i voti attuali e crea un rapporto comprensibile per chi ha partecipato.',
  generate: 'Finalizza e crea il rapporto',
  regenerate: 'Crea una nuova versione',
  generating: 'Preparazione del rapporto…',
  preview: 'Anteprima',
  hidePreview: 'Chiudi anteprima',
  publish: 'Pubblica il rapporto',
  published: 'Rapporto pubblicato',
  openReport: 'Apri il rapporto pubblico',
  draftReady: 'Bozza pronta per la revisione',
}

export function getReportCopy(language) {
  return COPY[language] || COPY.en
}
