const COPY = {
  en: {
    finalReport: 'Final report',
    version: 'Version',
    stale: 'Voting reopened after this report was published. The findings below reflect the earlier finalised snapshot.',
    openingTitle: 'What the room found',
    intro: ({ voterCount, statementCount, responseCount }) =>
      `${voterCount} people voted across ${statementCount} statements, contributing ${responseCount} responses. This report follows the strongest shared signals first, then shows where the conversation remains open.`,
    voters: 'people voted',
    statements: 'statements',
    responses: 'responses',
    takeawaysKicker: 'The story in brief',
    takeawaysTitle: 'Three findings to carry forward',
    takeawaysLead: 'These statements combine broad support with meaningful participation.',
    support: 'support',
    coverage: 'coverage',
    evidenceLabel: 'Voting evidence',
    moreEvidence: (count) => `${count} more supporting statement${count === 1 ? '' : 's'}`,
    commonKicker: 'Common ground',
    commonTitle: 'Where the room can begin',
    commonLead: 'These positions received the strongest combination of support and response coverage.',
    principlesKicker: 'Principles beneath the votes',
    principlesTitle: 'The values connecting these results',
    principlesLead: 'These principles summarise recurring ideas across several pieces of voting evidence.',
    overlapKicker: 'Held together',
    overlapTitle: 'People supported more than one priority at once',
    overlapLead: 'The voting did not always force an either-or choice. These overlaps show priorities that many participants held together.',
    both: 'supported both',
    leftOnly: 'only the first',
    rightOnly: 'only the second',
    neither: 'neither',
    jointResponses: 'people responded to both',
    opinionKicker: 'Different emphases',
    opinionTitle: 'People combined these priorities in different ways',
    opinionLead: 'The map shows recurring patterns among people with enough responses for comparison. The tendencies can overlap and should not be read as fixed camps.',
    tendency: 'Tendency',
    approximateShare: (value) => `${value} relative weight`,
    tendencyPriorities: 'Often emphasises',
    multiTendency: 'people reflected more than one tendency',
    densityShown: 'people shown in privacy-safe density cells',
    densitySuppressed: 'people omitted because their cell was too small',
    dimension: 'Main dimension',
    opinionUnavailable: 'There was not enough privacy-safe evidence to describe opinion tendencies.',
    questionsKicker: 'Still open',
    questionsTitle: 'Where another conversation is needed',
    questionsLead: 'These statements produced a more even division among people who took a position.',
    proposalKicker: 'A possible bridge',
    proposalTitle: 'The common-ground proposal',
    participantValidation: 'Participant validation',
    agreed: 'agreed',
    disagreed: 'disagreed',
    proposalUnvalidated: 'This proposal has not yet received participant validation.',
    nextKicker: 'What this means',
    nextTitle: 'A practical way forward',
    nextCommon: 'Start with the areas that already combine support and reach.',
    nextOpen: 'Keep the open questions visible instead of presenting them as settled.',
    nextCoverage: 'Treat lower-response findings as signals to investigate, not conclusions.',
    implicationsKicker: 'What this means',
    implicationsTitle: 'Possible implications',
    methodsTitle: 'How this report was produced',
    methodsIntro: 'The report is generated from the finalised voting snapshot.',
    minimumEvidence: 'Minimum evidence threshold',
    privacy: 'Privacy',
    privacyText: 'The public report contains aggregate counts only. It does not include participant identifiers or individual ballots.',
    opinionMethod: 'The opinion landscape uses a two-dimensional, Pol.is-inspired projection and overlapping tendency analysis. Density cells with fewer than five people are not shown.',
    narrativeMethod: 'AI was used to draft the editorial labels and explanations from aggregate evidence. It did not receive names or individual ballots, and its claims are linked to statement IDs.',
    generated: 'Generated',
    controlsTitle: 'Story report',
    controlsDesc: 'Freeze the current votes and generate a reader-facing report.',
    generate: 'Finalize and create report',
    regenerate: 'Generate a new version',
    generating: 'Preparing the report…',
    preview: 'Preview draft',
    hidePreview: 'Hide preview',
    publish: 'Publish report',
    published: 'Report published',
    openReport: 'Open public report',
    failed: 'The report could not be generated. Try again.',
    draftReady: 'Draft ready for review',
    staleDraft: 'Voting changed after this version was generated.',
  },
  zh: {
    finalReport: '成果報告',
    version: '版本',
    stale: '本報告發布後，投票已重新開放。以下內容反映的是先前定稿時的資料。',
    openingTitle: '這場討論告訴我們什麼',
    intro: ({ voterCount, statementCount, responseCount }) =>
      `${voterCount} 位參與者針對 ${statementCount} 項主張投票，共留下 ${responseCount} 筆回應。這份報告先呈現最明確的共同訊號，再說明仍待討論之處。`,
    voters: '位參與者投票',
    statements: '項主張',
    responses: '筆回應',
    takeawaysKicker: '先看重點',
    takeawaysTitle: '值得帶走的三項發現',
    takeawaysLead: '這些主張同時獲得較廣泛的支持，也有足夠的參與基礎。',
    support: '支持',
    coverage: '回應涵蓋率',
    evidenceLabel: '投票證據',
    moreEvidence: (count) => `另有 ${count} 項相關主張`,
    commonKicker: '共同基礎',
    commonTitle: '可以從哪些共識開始',
    commonLead: '以下主張兼具較高支持度與回應涵蓋率，是這場討論中最穩固的共同基礎。',
    principlesKicker: '投票背後的原則',
    principlesTitle: '串連這些結果的共同價值',
    principlesLead: '這些原則整理了多項投票證據中反覆出現的想法。',
    overlapKicker: '同時存在的期待',
    overlapTitle: '許多人同時支持不只一項優先目標',
    overlapLead: '投票結果不總是非此即彼。這些重疊顯示，參與者往往會同時重視不同面向。',
    both: '兩者都支持',
    leftOnly: '只支持第一項',
    rightOnly: '只支持第二項',
    neither: '兩者皆未支持',
    jointResponses: '位參與者皆有回應',
    opinionKicker: '不同的重視方式',
    opinionTitle: '參與者以不同方式組合這些優先目標',
    opinionLead: '這張圖呈現回應資料足以比較的參與者中，反覆出現的意見模式。各種傾向可能重疊，不代表固定陣營。',
    tendency: '意見傾向',
    approximateShare: (value) => `相對比重 ${value}`,
    tendencyPriorities: '較常重視',
    multiTendency: '位參與者同時呈現多種傾向',
    densityShown: '位參與者呈現在符合隱私門檻的區塊中',
    densitySuppressed: '位參與者因所在區塊人數過少而未顯示',
    dimension: '主要差異面向',
    opinionUnavailable: '目前的資料不足以在保護隱私的前提下呈現意見傾向。',
    questionsKicker: '仍待釐清',
    questionsTitle: '下一輪討論可以從這裡開始',
    questionsLead: '在有明確立場的參與者之間，以下主張呈現較平均的分歧。',
    proposalKicker: '可能的連結',
    proposalTitle: '共同基礎提案',
    participantValidation: '參與者驗證',
    agreed: '同意',
    disagreed: '不同意',
    proposalUnvalidated: '這項提案尚未經參與者驗證。',
    nextKicker: '這代表什麼',
    nextTitle: '接下來可以怎麼做',
    nextCommon: '先從兼具支持度與參與廣度的主張開始行動。',
    nextOpen: '保留尚未解決的問題，不把分歧包裝成共識。',
    nextCoverage: '回應較少的結果適合作為後續探索線索，不宜直接視為結論。',
    implicationsKicker: '這代表什麼',
    implicationsTitle: '可能的啟示',
    methodsTitle: '這份報告如何產生',
    methodsIntro: '本報告依據定稿當下的投票資料自動產生。',
    minimumEvidence: '最低證據門檻',
    privacy: '隱私處理',
    privacyText: '公開報告只呈現彙整後的數據，不包含參與者識別資訊或個別投票紀錄。',
    opinionMethod: '意見分布採用受 Pol.is 啟發的二維投影與重疊傾向分析；少於五人的密度區塊不會顯示。',
    narrativeMethod: 'AI 依據彙整後的證據草擬標題與說明，不會取得姓名或個別投票紀錄；敘事中的結論均連結至對應的主張編號。',
    generated: '產生時間',
    controlsTitle: '成果故事報告',
    controlsDesc: '固定目前的投票資料，產生一份方便參與者閱讀的成果報告。',
    generate: '定稿並產生報告',
    regenerate: '產生新版本',
    generating: '正在整理報告⋯',
    preview: '預覽草稿',
    hidePreview: '收起預覽',
    publish: '發布報告',
    published: '報告已發布',
    openReport: '開啟公開報告',
    failed: '報告產生失敗，請再試一次。',
    draftReady: '草稿已完成，等待確認',
    staleDraft: '這個版本產生後，投票內容已有變動。',
  },
}

COPY.de = {
  ...COPY.en,
  finalReport: 'Abschlussbericht',
  version: 'Version',
  stale: 'Die Abstimmung wurde nach Veröffentlichung dieses Berichts wieder geöffnet. Die Ergebnisse beziehen sich auf den früheren Datenstand.',
  openingTitle: 'Was die Gruppe herausgefunden hat',
  intro: ({ voterCount, statementCount, responseCount }) =>
    `${voterCount} Personen stimmten über ${statementCount} Aussagen ab und gaben ${responseCount} Antworten. Der Bericht beginnt mit den stärksten gemeinsamen Signalen und zeigt danach die offenen Fragen.`,
  voters: 'Abstimmende',
  statements: 'Aussagen',
  responses: 'Antworten',
  takeawaysKicker: 'Kurz gesagt',
  takeawaysTitle: 'Drei Erkenntnisse für den weiteren Weg',
  takeawaysLead: 'Diese Aussagen verbinden breite Zustimmung mit einer soliden Beteiligungsbasis.',
  support: 'Zustimmung',
  coverage: 'Beteiligung',
  evidenceLabel: 'Abstimmungsergebnis',
  moreEvidence: (count) => `${count} weitere unterstützende Aussage${count === 1 ? '' : 'n'}`,
  commonKicker: 'Gemeinsame Grundlage',
  commonTitle: 'Wo die Gruppe beginnen kann',
  commonLead: 'Diese Positionen verbinden die stärkste Zustimmung mit einer breiten Beteiligung.',
  principlesKicker: 'Prinzipien hinter den Stimmen',
  principlesTitle: 'Welche Werte die Ergebnisse verbinden',
  principlesLead: 'Diese Prinzipien fassen wiederkehrende Gedanken aus mehreren Abstimmungsergebnissen zusammen.',
  overlapKicker: 'Zusammen gedacht',
  overlapTitle: 'Mehrere Prioritäten wurden gleichzeitig unterstützt',
  overlapLead: 'Die Abstimmung verlangte nicht immer eine Entweder-oder-Entscheidung. Diese Überschneidungen zeigen Prioritäten, die viele gemeinsam vertraten.',
  both: 'beides unterstützt',
  leftOnly: 'nur die erste',
  rightOnly: 'nur die zweite',
  neither: 'keine von beiden',
  jointResponses: 'Personen beantworteten beide',
  opinionKicker: 'Unterschiedliche Gewichtungen',
  opinionTitle: 'Prioritäten wurden unterschiedlich miteinander verbunden',
  opinionLead: 'Die Karte zeigt wiederkehrende Muster bei Personen mit genügend Antworten für einen Vergleich. Die Tendenzen können sich überschneiden und sind keine festen Lager.',
  tendency: 'Tendenz',
  approximateShare: (value) => `${value} relatives Gewicht`,
  tendencyPriorities: 'Häufig betont',
  multiTendency: 'Personen zeigten mehr als eine Tendenz',
  densityShown: 'Personen in datenschutzkonformen Dichtefeldern',
  densitySuppressed: 'Personen wegen zu kleiner Felder nicht dargestellt',
  dimension: 'Zentrale Dimension',
  opinionUnavailable: 'Für eine datenschutzkonforme Darstellung der Meinungstendenzen lagen nicht genügend Daten vor.',
  questionsKicker: 'Noch offen',
  questionsTitle: 'Wo ein weiteres Gespräch nötig ist',
  questionsLead: 'Bei diesen Aussagen war die Gruppe unter den Personen mit klarer Position gleichmässiger geteilt.',
  proposalKicker: 'Eine mögliche Brücke',
  proposalTitle: 'Der Vorschlag für eine gemeinsame Grundlage',
  participantValidation: 'Bestätigung durch Teilnehmende',
  agreed: 'stimmten zu',
  disagreed: 'stimmten nicht zu',
  proposalUnvalidated: 'Dieser Vorschlag wurde noch nicht von Teilnehmenden bestätigt.',
  nextKicker: 'Was das bedeutet',
  nextTitle: 'Ein praktischer Weg nach vorn',
  nextCommon: 'Mit den Bereichen beginnen, die bereits Zustimmung und Reichweite verbinden.',
  nextOpen: 'Offene Fragen sichtbar lassen, statt sie als geklärt darzustellen.',
  nextCoverage: 'Ergebnisse mit weniger Antworten als Hinweise verstehen, nicht als Schlussfolgerungen.',
  implicationsKicker: 'Was das bedeutet',
  implicationsTitle: 'Mögliche Folgerungen',
  methodsTitle: 'Wie dieser Bericht erstellt wurde',
  methodsIntro: 'Der Bericht wird aus dem finalisierten Abstimmungsstand erzeugt.',
  minimumEvidence: 'Mindestschwelle für Evidenz',
  privacy: 'Datenschutz',
  privacyText: 'Der öffentliche Bericht enthält nur aggregierte Zahlen, keine Kennungen oder individuellen Stimmabgaben.',
  opinionMethod: 'Die Meinungslandschaft nutzt eine von Pol.is inspirierte zweidimensionale Projektion und eine Analyse überlappender Tendenzen. Dichtefelder mit weniger als fünf Personen werden nicht gezeigt.',
  narrativeMethod: 'KI formulierte redaktionelle Bezeichnungen und Erklärungen aus aggregierten Daten. Sie erhielt weder Namen noch individuelle Stimmabgaben; Aussagen sind mit den jeweiligen Aussage-IDs verknüpft.',
  generated: 'Erstellt',
  controlsTitle: 'Ergebnisbericht',
  controlsDesc: 'Den aktuellen Abstimmungsstand festhalten und einen verständlichen Bericht erstellen.',
  generate: 'Finalisieren und Bericht erstellen',
  regenerate: 'Neue Version erstellen',
  generating: 'Bericht wird vorbereitet…',
  preview: 'Entwurf ansehen',
  hidePreview: 'Vorschau schließen',
  publish: 'Bericht veröffentlichen',
  published: 'Bericht veröffentlicht',
  openReport: 'Öffentlichen Bericht öffnen',
  failed: 'Der Bericht konnte nicht erstellt werden. Bitte erneut versuchen.',
  draftReady: 'Entwurf zur Prüfung bereit',
  staleDraft: 'Die Abstimmung hat sich seit der Erstellung dieser Version verändert.',
}

COPY.fr = {
  ...COPY.en,
  finalReport: 'Rapport final',
  stale: 'Le vote a été rouvert après la publication de ce rapport. Les résultats ci-dessous correspondent à la version finalisée précédente.',
  openingTitle: 'Ce que le groupe a fait ressortir',
  intro: ({ voterCount, statementCount, responseCount }) =>
    `${voterCount} personnes ont voté sur ${statementCount} propositions et fourni ${responseCount} réponses. Le rapport présente d’abord les signaux communs les plus solides, puis les questions encore ouvertes.`,
  voters: 'personnes ont voté',
  statements: 'propositions',
  responses: 'réponses',
  takeawaysKicker: 'En bref',
  takeawaysTitle: 'Trois enseignements à retenir',
  takeawaysLead: 'Ces propositions associent un large soutien à une participation significative.',
  support: 'de soutien',
  coverage: 'de participation',
  evidenceLabel: 'Résultat du vote',
  moreEvidence: (count) => `${count} autre${count === 1 ? '' : 's'} proposition${count === 1 ? '' : 's'} à l’appui`,
  commonKicker: 'Terrain d’entente',
  commonTitle: 'Les points de départ communs',
  commonLead: 'Ces positions réunissent la combinaison la plus solide de soutien et de participation.',
  principlesKicker: 'Les principes derrière les votes',
  principlesTitle: 'Les valeurs qui relient ces résultats',
  principlesLead: 'Ces principes résument des idées récurrentes dans plusieurs résultats de vote.',
  overlapKicker: 'Des priorités tenues ensemble',
  overlapTitle: 'Plusieurs priorités ont été soutenues ensemble',
  overlapLead: 'Le vote n’imposait pas toujours un choix binaire. Ces chevauchements montrent les priorités que de nombreuses personnes ont soutenues simultanément.',
  both: 'ont soutenu les deux',
  leftOnly: 'seulement la première',
  rightOnly: 'seulement la seconde',
  neither: 'aucune des deux',
  jointResponses: 'personnes ont répondu aux deux',
  opinionKicker: 'Des accents différents',
  opinionTitle: 'Les priorités ont été combinées de différentes manières',
  opinionLead: 'La carte montre des schémas récurrents chez les personnes ayant assez répondu pour être comparées. Les tendances peuvent se chevaucher et ne constituent pas des camps fixes.',
  tendency: 'Tendance',
  approximateShare: (value) => `Poids relatif ${value}`,
  tendencyPriorities: 'Souligne souvent',
  multiTendency: 'personnes reflétaient plusieurs tendances',
  densityShown: 'personnes dans des zones conformes au seuil de confidentialité',
  densitySuppressed: 'personnes non affichées car leur zone était trop petite',
  dimension: 'Dimension principale',
  opinionUnavailable: 'Les données étaient insuffisantes pour décrire les tendances d’opinion tout en protégeant la confidentialité.',
  questionsKicker: 'Encore ouvert',
  questionsTitle: 'Les sujets qui demandent encore du dialogue',
  questionsLead: 'Ces propositions ont produit un partage plus équilibré parmi les personnes ayant pris position.',
  proposalKicker: 'Un pont possible',
  proposalTitle: 'La proposition de terrain d’entente',
  participantValidation: 'Validation des participantes et participants',
  agreed: 'd’accord',
  disagreed: 'pas d’accord',
  proposalUnvalidated: 'Cette proposition n’a pas encore été validée par les participantes et participants.',
  nextKicker: 'Ce que cela implique',
  nextTitle: 'Une voie concrète pour la suite',
  nextCommon: 'Commencer par les domaines qui associent déjà soutien et portée.',
  nextOpen: 'Garder les questions ouvertes visibles sans les présenter comme réglées.',
  nextCoverage: 'Considérer les résultats moins renseignés comme des pistes à explorer, non comme des conclusions.',
  implicationsKicker: 'Ce que cela implique',
  implicationsTitle: 'Implications possibles',
  methodsTitle: 'Comment ce rapport a été produit',
  methodsIntro: 'Le rapport est généré à partir de l’instantané finalisé du vote.',
  minimumEvidence: 'Seuil minimal de données',
  privacy: 'Confidentialité',
  privacyText: 'Le rapport public ne contient que des données agrégées, sans identifiant ni bulletin individuel.',
  opinionMethod: 'Le paysage d’opinion utilise une projection bidimensionnelle inspirée de Pol.is et une analyse de tendances qui se chevauchent. Les zones comptant moins de cinq personnes ne sont pas affichées.',
  narrativeMethod: 'L’IA a formulé les intitulés et explications à partir de données agrégées. Elle n’a reçu aucun nom ni vote individuel, et chaque affirmation est reliée aux identifiants des propositions.',
  generated: 'Généré',
  controlsTitle: 'Rapport de résultats',
  controlsDesc: 'Figer les votes actuels et créer un rapport accessible aux participantes et participants.',
  generate: 'Finaliser et créer le rapport',
  regenerate: 'Créer une nouvelle version',
  generating: 'Préparation du rapport…',
  preview: 'Prévisualiser',
  hidePreview: 'Fermer l’aperçu',
  publish: 'Publier le rapport',
  published: 'Rapport publié',
  openReport: 'Ouvrir le rapport public',
  failed: 'Le rapport n’a pas pu être généré. Veuillez réessayer.',
  draftReady: 'Brouillon prêt à être vérifié',
  staleDraft: 'Le vote a changé depuis la création de cette version.',
}

COPY.it = {
  ...COPY.en,
  finalReport: 'Rapporto finale',
  stale: 'La votazione è stata riaperta dopo la pubblicazione del rapporto. I risultati riflettono la precedente istantanea finalizzata.',
  openingTitle: 'Che cosa è emerso dal gruppo',
  intro: ({ voterCount, statementCount, responseCount }) =>
    `${voterCount} persone hanno votato su ${statementCount} affermazioni, fornendo ${responseCount} risposte. Il rapporto parte dai segnali condivisi più solidi e passa poi alle questioni ancora aperte.`,
  voters: 'persone hanno votato',
  statements: 'affermazioni',
  responses: 'risposte',
  takeawaysKicker: 'In breve',
  takeawaysTitle: 'Tre risultati da portare avanti',
  takeawaysLead: 'Queste affermazioni uniscono un ampio sostegno a una partecipazione significativa.',
  support: 'sostegno',
  coverage: 'partecipazione',
  evidenceLabel: 'Risultato del voto',
  moreEvidence: (count) => `${count} altr${count === 1 ? 'a' : 'e'} affermazion${count === 1 ? 'e' : 'i'} a sostegno`,
  commonKicker: 'Terreno comune',
  commonTitle: 'Da dove può partire il gruppo',
  commonLead: 'Queste posizioni hanno ottenuto la combinazione più forte di sostegno e partecipazione.',
  principlesKicker: 'I principi dietro i voti',
  principlesTitle: 'I valori che collegano questi risultati',
  principlesLead: 'Questi principi riassumono idee ricorrenti in più risultati della votazione.',
  overlapKicker: 'Priorità tenute insieme',
  overlapTitle: 'Più priorità sono state sostenute insieme',
  overlapLead: 'La votazione non imponeva sempre una scelta alternativa. Queste sovrapposizioni mostrano priorità sostenute contemporaneamente da molte persone.',
  both: 'hanno sostenuto entrambe',
  leftOnly: 'solo la prima',
  rightOnly: 'solo la seconda',
  neither: 'nessuna delle due',
  jointResponses: 'persone hanno risposto a entrambe',
  opinionKicker: 'Accenti diversi',
  opinionTitle: 'Le priorità sono state combinate in modi diversi',
  opinionLead: 'La mappa mostra schemi ricorrenti tra le persone con abbastanza risposte per il confronto. Le tendenze possono sovrapporsi e non sono schieramenti fissi.',
  tendency: 'Tendenza',
  approximateShare: (value) => `Peso relativo ${value}`,
  tendencyPriorities: 'Sottolinea spesso',
  multiTendency: 'persone riflettevano più di una tendenza',
  densityShown: 'persone nelle aree conformi alla soglia di riservatezza',
  densitySuppressed: 'persone non mostrate perché la loro area era troppo piccola',
  dimension: 'Dimensione principale',
  opinionUnavailable: 'I dati non erano sufficienti per descrivere le tendenze di opinione tutelando la riservatezza.',
  questionsKicker: 'Ancora aperto',
  questionsTitle: 'Dove serve un altro confronto',
  questionsLead: 'Queste affermazioni hanno diviso in modo più equilibrato le persone che hanno preso posizione.',
  proposalKicker: 'Un possibile ponte',
  proposalTitle: 'La proposta di terreno comune',
  participantValidation: 'Validazione dei partecipanti',
  agreed: 'd’accordo',
  disagreed: 'in disaccordo',
  proposalUnvalidated: 'Questa proposta non è ancora stata validata dai partecipanti.',
  nextKicker: 'Che cosa significa',
  nextTitle: 'Un percorso pratico per il futuro',
  nextCommon: 'Partire dagli ambiti che già uniscono sostegno e portata.',
  nextOpen: 'Mantenere visibili le questioni aperte senza presentarle come risolte.',
  nextCoverage: 'Trattare i risultati con meno risposte come segnali da approfondire, non come conclusioni.',
  implicationsKicker: 'Che cosa significa',
  implicationsTitle: 'Possibili implicazioni',
  methodsTitle: 'Come è stato prodotto il rapporto',
  methodsIntro: 'Il rapporto viene generato dall’istantanea finale della votazione.',
  minimumEvidence: 'Soglia minima di evidenza',
  privacy: 'Riservatezza',
  privacyText: 'Il rapporto pubblico contiene solo dati aggregati, senza identificativi o voti individuali.',
  opinionMethod: 'Il panorama delle opinioni usa una proiezione bidimensionale ispirata a Pol.is e un’analisi di tendenze sovrapposte. Le aree con meno di cinque persone non vengono mostrate.',
  narrativeMethod: 'L’IA ha formulato titoli e spiegazioni a partire da dati aggregati. Non ha ricevuto nomi o voti individuali e ogni affermazione è collegata agli identificativi delle proposte.',
  generated: 'Generato',
  controlsTitle: 'Rapporto dei risultati',
  controlsDesc: 'Fissa i voti attuali e crea un rapporto comprensibile per chi ha partecipato.',
  generate: 'Finalizza e crea il rapporto',
  regenerate: 'Crea una nuova versione',
  generating: 'Preparazione del rapporto…',
  preview: 'Anteprima',
  hidePreview: 'Chiudi anteprima',
  publish: 'Pubblica il rapporto',
  published: 'Rapporto pubblicato',
  openReport: 'Apri il rapporto pubblico',
  failed: 'Non è stato possibile generare il rapporto. Riprova.',
  draftReady: 'Bozza pronta per la revisione',
  staleDraft: 'La votazione è cambiata da quando è stata creata questa versione.',
}

export function getReportCopy(language) {
  return COPY[language] || COPY.en
}
